In [56]:
# getting our grunglas data
import pandas as pd
df = pd.read_csv("./fuellstandsensoren-glassammelstellen-gruenglas.csv", sep = ";")
df

,measured_at,data,device_id,name,id,location,data_distance,geo_point_2d
0,2020-11-28T22:43:55+01:00,"{""type"": ""reading"", ""distance"": 838}",e785cb18-96e1-4215-931a-82a731d2ee5a,107096 | 4814,158c16a5-75c0-40e0-82aa-c976ef9660fb,"{""coordinates"": [9.39166, 47.43514], ""type"": ""...",838.0,"47.43514, 9.39166"
1,2020-11-28T22:43:22+01:00,"{""type"": ""reading"", ""distance"": 1548}",5fe079a9-6e53-4a9d-b974-eca5d0916632,107112 | 2B88,ee65bf04-fa7d-4ad9-a81f-47cd2a38e626,"{""coordinates"": [9.391704108835626, 47.4351514...",1548.0,"47.4351514110773, 9.391704108835626"
2,2020-11-28T22:40:56+01:00,"{""type"": ""reading"", ""distance"": 817}",b4d0f672-6436-483e-a0cd-fab4fe552a8c,104243,2d1a7e3f-ae62-4d64-9833-0b8000ad18e9,"{""coordinates"": [9.37393, 47.42701], ""type"": ""...",817.0,"47.42701, 9.37393"
3,2020-11-28T22:40:41+01:00,"{""type"": ""reading"", ""distance"": 2500}",b5b36857-0f47-4df9-8c8a-0ff431875b18,104246,ddd148a9-3762-4081-a16b-1c90cfe1e474,"{""coordinates"": [9.36637, 47.41634], ""type"": ""...",2500.0,"47.41634, 9.36637"
4,2020-11-28T22:38:19+01:00,"{""type"": ""reading"", ""distance"": 989}",7f9cad51-8a0c-4fa9-a6d4-8cf649d819ab,107048 | 671B,02b72973-e7b3-459c-81b5-f1f2f225b75a,"{""coordinates"": [9.38269, 47.41539], ""type"": ""...",989.0,"47.41539, 9.38269"
...,...,...,...,...,...,...,...,...
892928,2023-08-18T18:41:55+02:00,"{""type"": ""reading"", ""distance"": 1290}",aae16e11-7f7e-4251-9e73-fd836db67b79,107055 | 2C76,0dc78174-14d8-401a-baf1-1f57d634bab4,"{""coordinates"": [9.39314, 47.42541], ""type"": ""...",1290.0,"47.42541, 9.39314"
892929,2023-08-18T18:36:39+02:00,"{""type"": ""reading"", ""distance"": 1376}",cfcfb74d-b13e-43fb-bc59-9eee4f6be818,107038 | 2B8D,796b3fe0-641a-43e0-af6a-527a1ee9ae51,"{""coordinates"": [9.36611, 47.41086], ""type"": ""...",1376.0,"47.41086, 9.36611"
892930,2023-08-18T18:25:33+02:00,"{""type"": ""reading"", ""distance"": 1483}",496ebab5-e27f-46a4-91bd-28e5086eb594,107108 | 0AEA,134d1529-9637-4873-8047-65bdfbdbd50c,"{""coordinates"": [9.38204, 47.42595], ""type"": ""...",1483.0,"47.42595, 9.38204"
892931,2023-08-18T17:55:33+02:00,"{""type"": ""reading"", ""distance"": 1462}",496ebab5-e27f-46a4-91bd-28e5086eb594,107108 | 0AEA,141d9269-4601-4d84-ac78-7e4b13b6326a,"{""coordinates"": [9.38204, 47.42595], ""type"": ""...",1462.0,"47.42595, 9.38204"
892932,2023-08-18T17:41:55+02:00,"{""type"": ""reading"", ""distance"": 1247}",aae16e11-7f7e-4251-9e73-fd836db67b79,107055 | 2C76,64511fd0-381d-40a7-931b-dc1a327aa434,"{""coordinates"": [9.39314, 47.42541], ""type"": ""...",1247.0,"47.42541, 9.39314"

In [57]:
# creating datetime columns
df["measured_at"] = pd.to_datetime(df["measured_at"], utc=True)
df["time_uct"] = df["measured_at"].dt.time
df["date_uct"] = df["measured_at"].dt.date
df

,measured_at,data,device_id,name,id,location,data_distance,geo_point_2d,time_uct,date_uct
0,2020-11-28 21:43:55+00:00,"{""type"": ""reading"", ""distance"": 838}",e785cb18-96e1-4215-931a-82a731d2ee5a,107096 | 4814,158c16a5-75c0-40e0-82aa-c976ef9660fb,"{""coordinates"": [9.39166, 47.43514], ""type"": ""...",838.0,"47.43514, 9.39166",21:43:55,2020-11-28
1,2020-11-28 21:43:22+00:00,"{""type"": ""reading"", ""distance"": 1548}",5fe079a9-6e53-4a9d-b974-eca5d0916632,107112 | 2B88,ee65bf04-fa7d-4ad9-a81f-47cd2a38e626,"{""coordinates"": [9.391704108835626, 47.4351514...",1548.0,"47.4351514110773, 9.391704108835626",21:43:22,2020-11-28
2,2020-11-28 21:40:56+00:00,"{""type"": ""reading"", ""distance"": 817}",b4d0f672-6436-483e-a0cd-fab4fe552a8c,104243,2d1a7e3f-ae62-4d64-9833-0b8000ad18e9,"{""coordinates"": [9.37393, 47.42701], ""type"": ""...",817.0,"47.42701, 9.37393",21:40:56,2020-11-28
3,2020-11-28 21:40:41+00:00,"{""type"": ""reading"", ""distance"": 2500}",b5b36857-0f47-4df9-8c8a-0ff431875b18,104246,ddd148a9-3762-4081-a16b-1c90cfe1e474,"{""coordinates"": [9.36637, 47.41634], ""type"": ""...",2500.0,"47.41634, 9.36637",21:40:41,2020-11-28
4,2020-11-28 21:38:19+00:00,"{""type"": ""reading"", ""distance"": 989}",7f9cad51-8a0c-4fa9-a6d4-8cf649d819ab,107048 | 671B,02b72973-e7b3-459c-81b5-f1f2f225b75a,"{""coordinates"": [9.38269, 47.41539], ""type"": ""...",989.0,"47.41539, 9.38269",21:38:19,2020-11-28
...,...,...,...,...,...,...,...,...,...,...
892928,2023-08-18 16:41:55+00:00,"{""type"": ""reading"", ""distance"": 1290}",aae16e11-7f7e-4251-9e73-fd836db67b79,107055 | 2C76,0dc78174-14d8-401a-baf1-1f57d634bab4,"{""coordinates"": [9.39314, 47.42541], ""type"": ""...",1290.0,"47.42541, 9.39314",16:41:55,2023-08-18
892929,2023-08-18 16:36:39+00:00,"{""type"": ""reading"", ""distance"": 1376}",cfcfb74d-b13e-43fb-bc59-9eee4f6be818,107038 | 2B8D,796b3fe0-641a-43e0-af6a-527a1ee9ae51,"{""coordinates"": [9.36611, 47.41086], ""type"": ""...",1376.0,"47.41086, 9.36611",16:36:39,2023-08-18
892930,2023-08-18 16:25:33+00:00,"{""type"": ""reading"", ""distance"": 1483}",496ebab5-e27f-46a4-91bd-28e5086eb594,107108 | 0AEA,134d1529-9637-4873-8047-65bdfbdbd50c,"{""coordinates"": [9.38204, 47.42595], ""type"": ""...",1483.0,"47.42595, 9.38204",16:25:33,2023-08-18
892931,2023-08-18 15:55:33+00:00,"{""type"": ""reading"", ""distance"": 1462}",496ebab5-e27f-46a4-91bd-28e5086eb594,107108 | 0AEA,141d9269-4601-4d84-ac78-7e4b13b6326a,"{""coordinates"": [9.38204, 47.42595], ""type"": ""...",1462.0,"47.42595, 9.38204",15:55:33,2023-08-18
892932,2023-08-18 15:41:55+00:00,"{""type"": ""reading"", ""distance"": 1247}",aae16e11-7f7e-4251-9e73-fd836db67b79,107055 | 2C76,64511fd0-381d-40a7-931b-dc1a327aa434,"{""coordinates"": [9.39314, 47.42541], ""type"": ""...",1247.0,"47.42541, 9.39314",15:41:55,2023-08-18

In [58]:
# sorting the values
df.sort_values(by='measured_at', inplace=True)
df

,measured_at,data,device_id,name,id,location,data_distance,geo_point_2d,time_uct,date_uct
690036,2020-01-01 00:01:03+00:00,"{""foo"": 3}",2e4a8f6d-d398-4749-bc74-a24efa3f5644,107123 | 980F,4e1f3cfc-e265-4bde-8500-36974fc5968a,"{""coordinates"": [9.36053, 47.42574], ""type"": ""...",NaN,"47.42574, 9.36053",00:01:03,2020-01-01
98089,2020-01-01 00:01:16+00:00,"{""foo"": 3}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,403f2bc4-f68a-4d6b-8ffc-ca64f693a8e9,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388",00:01:16,2020-01-01
406734,2020-01-01 00:03:19+00:00,"{""foo"": 3}",b5b36857-0f47-4df9-8c8a-0ff431875b18,104246,0b999403-5406-4344-b5ae-aa2525624f4b,"{""coordinates"": [9.36637, 47.41634], ""type"": ""...",NaN,"47.41634, 9.36637",00:03:19,2020-01-01
690035,2020-01-01 00:17:21+00:00,"{""foo"": 3}",62ec2345-9665-4fd2-9fa7-91ead95dc99b,107031 | 6348,40b7b7f0-3fc1-4d69-a33c-511bec6541af,"{""coordinates"": [9.29952, 47.40395], ""type"": ""...",NaN,"47.40395, 9.29952",00:17:21,2020-01-01
98087,2020-01-01 00:17:32+00:00,"{""foo"": 3}",a82a9f13-4ec0-45bd-a218-4e2cc4ca11bb,107070 | 454B,f6d0e6eb-9859-434d-8649-ba4eaa36aab8,"{""coordinates"": [9.338409956002408, 47.4078311...",NaN,"47.407831127695545, 9.338409956002408",00:17:32,2020-01-01
...,...,...,...,...,...,...,...,...,...,...
806035,2023-11-30 22:32:32+00:00,"{""type"": ""reading"", ""distance"": 1032}",aae16e11-7f7e-4251-9e73-fd836db67b79,107055 | 2C76,1451428d-377c-4c31-899c-cabf14ee252f,"{""coordinates"": [9.39314, 47.42541], ""type"": ""...",1032.0,"47.42541, 9.39314",22:32:32,2023-11-30
693340,2023-11-30 22:36:24+00:00,"{""type"": ""reading"", ""distance"": 1376}",7f9cad51-8a0c-4fa9-a6d4-8cf649d819ab,107048 | 671B,eb27bbd1-7d92-44b6-9504-d74973ec7b53,"{""coordinates"": [9.38269, 47.41539], ""type"": ""...",1376.0,"47.41539, 9.38269",22:36:24,2023-11-30
876871,2023-11-30 22:47:32+00:00,"{""type"": ""reading"", ""distance"": 1290}",a3e91e80-9b8d-4bd6-bbd7-011319e05a0c,107068 | 4455,a8ee9a3a-7714-46b6-a775-c184a9ccaa0a,"{""coordinates"": [9.33586, 47.41208], ""type"": ""...",1290.0,"47.41208, 9.33586",22:47:32,2023-11-30
876870,2023-11-30 22:47:33+00:00,"{""type"": ""reading"", ""distance"": 1569}",496ebab5-e27f-46a4-91bd-28e5086eb594,107108 | 0AEA,922b4584-2a83-405c-938f-9783c330c4ec,"{""coordinates"": [9.38204, 47.42595], ""type"": ""...",1569.0,"47.42595, 9.38204",22:47:33,2023-11-30
883052,2023-11-30 22:58:45+00:00,"{""type"": ""reading"", ""distance"": 1268}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,7d351916-a40c-4920-ac35-00bb78d99b97,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",1268.0,"47.40798, 9.33388",22:58:45,2023-11-30

In [59]:
# medium quality id inspection
#Device ID
#8a6b6d27-9149-40ea-88b6-0c0d7446a0df
#cfcfb74d-b13e-43fb-bc59-9eee4f6be818
#62ec2345-9665-4fd2-9fa7-91ead95dc99b
#b4d0f672-6436-483e-a0cd-fab4fe552a8c
#2e4a8f6d-d398-4749-bc74-a24efa3f5644
#134fc269-ec25-466f-82e7-780beb314108

In [60]:
# finding last day where there was a value for data_distance
df.loc[df["device_id"] == "134fc269-ec25-466f-82e7-780beb314108"]

,measured_at,data,device_id,name,id,location,data_distance,geo_point_2d,time_uct,date_uct
52461,2020-06-16 14:21:58+00:00,"{""type"": ""reading"", ""distance"": 1204}",134fc269-ec25-466f-82e7-780beb314108,107034 | 8104,88e6caea-3b37-42ce-af12-0bc2b25ce52a,"{""coordinates"": [9.40665, 47.43919], ""type"": ""...",1204.0,"47.43919, 9.40665",14:21:58,2020-06-16
52451,2020-06-16 14:51:58+00:00,"{""type"": ""reading"", ""distance"": 1204}",134fc269-ec25-466f-82e7-780beb314108,107034 | 8104,fff7a45e-d91f-435e-aef3-2bfffc07ea88,"{""coordinates"": [9.40665, 47.43919], ""type"": ""...",1204.0,"47.43919, 9.40665",14:51:58,2020-06-16
380422,2020-06-16 15:21:58+00:00,"{""type"": ""reading"", ""distance"": 1204}",134fc269-ec25-466f-82e7-780beb314108,107034 | 8104,2d3a2deb-a1f9-40fc-bc6d-66cceb277f06,"{""coordinates"": [9.40665, 47.43919], ""type"": ""...",1204.0,"47.43919, 9.40665",15:21:58,2020-06-16
380400,2020-06-16 16:21:58+00:00,"{""type"": ""reading"", ""distance"": 1225}",134fc269-ec25-466f-82e7-780beb314108,107034 | 8104,7ca43f30-e825-4038-94ac-061f9a96a7ee,"{""coordinates"": [9.40665, 47.43919], ""type"": ""...",1225.0,"47.43919, 9.40665",16:21:58,2020-06-16
788828,2020-06-16 16:51:57+00:00,"{""type"": ""reading"", ""distance"": 1247}",134fc269-ec25-466f-82e7-780beb314108,107034 | 8104,f505861d-ce00-4af2-9f41-406078f03814,"{""coordinates"": [9.40665, 47.43919], ""type"": ""...",1247.0,"47.43919, 9.40665",16:51:57,2020-06-16
...,...,...,...,...,...,...,...,...,...,...
882473,2023-10-19 13:23:44+00:00,"{""type"": ""reading"", ""distance"": 709}",134fc269-ec25-466f-82e7-780beb314108,107034 | 8104,df1c0ce6-29be-43bd-9641-4066281fef0a,"{""coordinates"": [9.40665, 47.43919], ""type"": ""...",709.0,"47.43919, 9.40665",13:23:44,2023-10-19
880217,2023-10-19 14:23:44+00:00,"{""type"": ""reading"", ""distance"": 688}",134fc269-ec25-466f-82e7-780beb314108,107034 | 8104,c2374f53-51d3-4d45-98f3-a99b2f4281e0,"{""coordinates"": [9.40665, 47.43919], ""type"": ""...",688.0,"47.43919, 9.40665",14:23:44,2023-10-19
880214,2023-10-19 14:53:43+00:00,"{""type"": ""reading"", ""distance"": 688}",134fc269-ec25-466f-82e7-780beb314108,107034 | 8104,2e08942b-c401-46a4-bcbe-7d968cd8d51a,"{""coordinates"": [9.40665, 47.43919], ""type"": ""...",688.0,"47.43919, 9.40665",14:53:43,2023-10-19
882467,2023-10-19 15:23:43+00:00,"{""type"": ""reading"", ""distance"": 709}",134fc269-ec25-466f-82e7-780beb314108,107034 | 8104,f6859ad1-b7c6-4aef-b06b-3580e3eb7c23,"{""coordinates"": [9.40665, 47.43919], ""type"": ""...",709.0,"47.43919, 9.40665",15:23:43,2023-10-19
880210,2023-10-19 15:53:43+00:00,"{""type"": ""reading"", ""distance"": 645}",134fc269-ec25-466f-82e7-780beb314108,107034 | 8104,6918f065-6d4d-419b-8b26-9969ed1e16fb,"{""coordinates"": [9.40665, 47.43919], ""type"": ""...",645.0,"47.43919, 9.40665",15:53:43,2023-10-19

In [61]:
#Good quality id check
#aae16e11-7f7e-4251-9e73-fd836db67b79
#7f9cad51-8a0c-4fa9-a6d4-8cf649d819ab
#496ebab5-e27f-46a4-91bd-28e5086eb594
#96e70afa-3ce0-4674-a331-8b85aed97068
#a3e91e80-9b8d-4bd6-bbd7-011319e05a0c

# finding last day where there was a value for data_distance
df.loc[df["device_id"] == "a3e91e80-9b8d-4bd6-bbd7-011319e05a0c"]

,measured_at,data,device_id,name,id,location,data_distance,geo_point_2d,time_uct,date_uct
645313,2020-06-16 14:11:19+00:00,"{""type"": ""reading"", ""distance"": 1247}",a3e91e80-9b8d-4bd6-bbd7-011319e05a0c,107068 | 4455,f40184e8-3507-40ca-b695-0e8b2d5142c6,"{""coordinates"": [9.33586, 47.41208], ""type"": ""...",1247.0,"47.41208, 9.33586",14:11:19,2020-06-16
645309,2020-06-16 14:41:19+00:00,"{""type"": ""reading"", ""distance"": 1204}",a3e91e80-9b8d-4bd6-bbd7-011319e05a0c,107068 | 4455,7896061a-7dac-472f-8362-7d8bc70ad269,"{""coordinates"": [9.33586, 47.41208], ""type"": ""...",1204.0,"47.41208, 9.33586",14:41:19,2020-06-16
380426,2020-06-16 15:11:19+00:00,"{""type"": ""reading"", ""distance"": 1204}",a3e91e80-9b8d-4bd6-bbd7-011319e05a0c,107068 | 4455,c55e7bed-172a-4a81-9588-1c0b2ee98c17,"{""coordinates"": [9.33586, 47.41208], ""type"": ""...",1204.0,"47.41208, 9.33586",15:11:19,2020-06-16
159886,2020-06-16 15:41:19+00:00,"{""type"": ""reading"", ""distance"": 1247}",a3e91e80-9b8d-4bd6-bbd7-011319e05a0c,107068 | 4455,3ac14111-6407-4c85-afeb-606ec256106f,"{""coordinates"": [9.33586, 47.41208], ""type"": ""...",1247.0,"47.41208, 9.33586",15:41:19,2020-06-16
645296,2020-06-16 16:11:19+00:00,"{""type"": ""reading"", ""distance"": 1225}",a3e91e80-9b8d-4bd6-bbd7-011319e05a0c,107068 | 4455,f676b72d-d062-4d90-b1a5-e46eea9d301b,"{""coordinates"": [9.33586, 47.41208], ""type"": ""...",1225.0,"47.41208, 9.33586",16:11:19,2020-06-16
...,...,...,...,...,...,...,...,...,...,...
668071,2023-11-30 20:47:32+00:00,"{""type"": ""reading"", ""distance"": 1290}",a3e91e80-9b8d-4bd6-bbd7-011319e05a0c,107068 | 4455,36e27c37-fd6f-428c-9cfc-b74dd899aded,"{""coordinates"": [9.33586, 47.41208], ""type"": ""...",1290.0,"47.41208, 9.33586",20:47:32,2023-11-30
693344,2023-11-30 21:17:32+00:00,"{""type"": ""reading"", ""distance"": 1290}",a3e91e80-9b8d-4bd6-bbd7-011319e05a0c,107068 | 4455,550d899c-1633-4447-a355-6120ba669583,"{""coordinates"": [9.33586, 47.41208], ""type"": ""...",1290.0,"47.41208, 9.33586",21:17:32,2023-11-30
876872,2023-11-30 21:47:32+00:00,"{""type"": ""reading"", ""distance"": 1290}",a3e91e80-9b8d-4bd6-bbd7-011319e05a0c,107068 | 4455,3c83b7cf-e486-4316-a865-9f39234186ae,"{""coordinates"": [9.33586, 47.41208], ""type"": ""...",1290.0,"47.41208, 9.33586",21:47:32,2023-11-30
883053,2023-11-30 22:17:32+00:00,"{""type"": ""reading"", ""distance"": 1290}",a3e91e80-9b8d-4bd6-bbd7-011319e05a0c,107068 | 4455,cdc94c55-7ee9-4eff-bc0f-84425b552211,"{""coordinates"": [9.33586, 47.41208], ""type"": ""...",1290.0,"47.41208, 9.33586",22:17:32,2023-11-30
876871,2023-11-30 22:47:32+00:00,"{""type"": ""reading"", ""distance"": 1290}",a3e91e80-9b8d-4bd6-bbd7-011319e05a0c,107068 | 4455,a8ee9a3a-7714-46b6-a775-c184a9ccaa0a,"{""coordinates"": [9.33586, 47.41208], ""type"": ""...",1290.0,"47.41208, 9.33586",22:47:32,2023-11-30

In [62]:
# Bad quality ID check
#eaea0bcc-2970-41e1-8821-29be122a65b0
#3301af3b-a6fe-429e-8b01-c7b71249abdf
#11d4bcfe-bde2-42bd-8ebc-43ee77012480
#e785cb18-96e1-4215-931a-82a731d2ee5a
#36816c9e-3b69-4b8c-b9f7-150b0edf94db
#5fe079a9-6e53-4a9d-b974-eca5d0916632
#0b011106-e5fe-4202-92bd-c89abd042249
#b5b36857-0f47-4df9-8c8a-0ff431875b18
#1607ca61-c966-483d-bbfb-d97027d507c1
#79d9a5cb-3704-4a21-aedf-5989c70baed0
#e3a7cfea-c281-46fe-8758-0bf2388181c0
#e194deb4-afb0-4c83-aab2-71fcd13ca4e8
#a82a9f13-4ec0-45bd-a218-4e2cc4ca11bb
#f97fcfd4-a7a8-4839-958a-334d8c02566c

# finding last day where there was a value for data_distance
df.loc[df["device_id"] == "f97fcfd4-a7a8-4839-958a-334d8c02566c"]

,measured_at,data,device_id,name,id,location,data_distance,geo_point_2d,time_uct,date_uct
384768,2020-01-01 00:23:11+00:00,"{""foo"": 3}",f97fcfd4-a7a8-4839-958a-334d8c02566c,107107 | 657F,d11869fd-76d6-415e-96b7-6e60f22acb7c,"{""coordinates"": [9.379779148730364, 47.4194941...",NaN,"47.41949412694035, 9.379779148730364",00:23:11,2020-01-01
384765,2020-01-01 00:53:11+00:00,"{""foo"": 3}",f97fcfd4-a7a8-4839-958a-334d8c02566c,107107 | 657F,15fb081d-5a7b-4346-a82c-ac742d10c454,"{""coordinates"": [9.379779148730364, 47.4194941...",NaN,"47.41949412694035, 9.379779148730364",00:53:11,2020-01-01
98075,2020-01-01 01:23:10+00:00,"{""foo"": 3}",f97fcfd4-a7a8-4839-958a-334d8c02566c,107107 | 657F,297bc0eb-a2c2-4135-a811-da97692fc8ff,"{""coordinates"": [9.379779148730364, 47.4194941...",NaN,"47.41949412694035, 9.379779148730364",01:23:10,2020-01-01
759135,2020-01-01 01:53:10+00:00,"{""foo"": 3}",f97fcfd4-a7a8-4839-958a-334d8c02566c,107107 | 657F,8cb3b0ec-1c02-41d9-9f1b-7737f6879a68,"{""coordinates"": [9.379779148730364, 47.4194941...",NaN,"47.41949412694035, 9.379779148730364",01:53:10,2020-01-01
690023,2020-01-01 02:23:10+00:00,"{""foo"": 3}",f97fcfd4-a7a8-4839-958a-334d8c02566c,107107 | 657F,44d84bd5-6db6-4ae4-b707-1f52c7b4e878,"{""coordinates"": [9.379779148730364, 47.4194941...",NaN,"47.41949412694035, 9.379779148730364",02:23:10,2020-01-01
...,...,...,...,...,...,...,...,...,...,...
662081,2020-04-28 15:13:33+00:00,"{""foo"": 3}",f97fcfd4-a7a8-4839-958a-334d8c02566c,107107 | 657F,16bde11c-ed38-4044-b50a-24209d26b6b3,"{""coordinates"": [9.379779148730364, 47.4194941...",NaN,"47.41949412694035, 9.379779148730364",15:13:33,2020-04-28
776691,2020-04-28 15:43:33+00:00,"{""foo"": 3}",f97fcfd4-a7a8-4839-958a-334d8c02566c,107107 | 657F,1a7ec539-3161-44e3-ad75-fd5b0c14a050,"{""coordinates"": [9.379779148730364, 47.4194941...",NaN,"47.41949412694035, 9.379779148730364",15:43:33,2020-04-28
364910,2020-04-28 16:13:33+00:00,"{""foo"": 3}",f97fcfd4-a7a8-4839-958a-334d8c02566c,107107 | 657F,79f3189a-5ff2-40a2-87cf-c0a3039423ee,"{""coordinates"": [9.379779148730364, 47.4194941...",NaN,"47.41949412694035, 9.379779148730364",16:13:33,2020-04-28
776683,2020-04-28 16:43:33+00:00,"{""foo"": 3}",f97fcfd4-a7a8-4839-958a-334d8c02566c,107107 | 657F,456068be-b4d1-44d9-a4c8-2b331bc76564,"{""coordinates"": [9.379779148730364, 47.4194941...",NaN,"47.41949412694035, 9.379779148730364",16:43:33,2020-04-28
662076,2020-04-28 17:13:32+00:00,"{""foo"": 3}",f97fcfd4-a7a8-4839-958a-334d8c02566c,107107 | 657F,161419ab-6e28-4087-afd6-8d20bc18e3e2,"{""coordinates"": [9.379779148730364, 47.4194941...",NaN,"47.41949412694035, 9.379779148730364",17:13:32,2020-04-28

In [63]:
# getting rid of all nans
df = df.dropna()
df

,measured_at,data,device_id,name,id,location,data_distance,geo_point_2d,time_uct,date_uct
52467,2020-06-16 14:06:25+00:00,"{""type"": ""reading"", ""distance"": 1096}",e194deb4-afb0-4c83-aab2-71fcd13ca4e8,107131 | 808C,8a4a7611-45cd-41aa-a670-9ea5672ce108,"{""coordinates"": [9.39600777236538, 47.43095608...",1096.0,"47.43095608319004, 9.39600777236538",14:06:25,2020-06-16
159934,2020-06-16 14:06:27+00:00,"{""type"": ""reading"", ""distance"": 817}",eaea0bcc-2970-41e1-8821-29be122a65b0,107114 | 654B,400f37ec-a7c7-40c8-8ae5-7b7f54b74b40,"{""coordinates"": [9.391743082129409, 47.4351625...",817.0,"47.4351625218373, 9.391743082129409",14:06:27,2020-06-16
380442,2020-06-16 14:06:38+00:00,"{""type"": ""reading"", ""distance"": 1075}",11d4bcfe-bde2-42bd-8ebc-43ee77012480,107041 | 470A,f6375afb-0235-423c-82a2-4ac52d5eb917,"{""coordinates"": [9.346374054498114, 47.4196064...",1075.0,"47.41960640999497, 9.346374054498114",14:06:38,2020-06-16
788857,2020-06-16 14:07:41+00:00,"{""type"": ""reading"", ""distance"": 1075}",8a6b6d27-9149-40ea-88b6-0c0d7446a0df,107127 | 817E,7f794f7b-29a5-4ecb-9364-bf9172219251,"{""coordinates"": [9.37681, 47.43724], ""type"": ""...",1075.0,"47.43724, 9.37681",14:07:41,2020-06-16
645313,2020-06-16 14:11:19+00:00,"{""type"": ""reading"", ""distance"": 1247}",a3e91e80-9b8d-4bd6-bbd7-011319e05a0c,107068 | 4455,f40184e8-3507-40ca-b695-0e8b2d5142c6,"{""coordinates"": [9.33586, 47.41208], ""type"": ""...",1247.0,"47.41208, 9.33586",14:11:19,2020-06-16
...,...,...,...,...,...,...,...,...,...,...
806035,2023-11-30 22:32:32+00:00,"{""type"": ""reading"", ""distance"": 1032}",aae16e11-7f7e-4251-9e73-fd836db67b79,107055 | 2C76,1451428d-377c-4c31-899c-cabf14ee252f,"{""coordinates"": [9.39314, 47.42541], ""type"": ""...",1032.0,"47.42541, 9.39314",22:32:32,2023-11-30
693340,2023-11-30 22:36:24+00:00,"{""type"": ""reading"", ""distance"": 1376}",7f9cad51-8a0c-4fa9-a6d4-8cf649d819ab,107048 | 671B,eb27bbd1-7d92-44b6-9504-d74973ec7b53,"{""coordinates"": [9.38269, 47.41539], ""type"": ""...",1376.0,"47.41539, 9.38269",22:36:24,2023-11-30
876871,2023-11-30 22:47:32+00:00,"{""type"": ""reading"", ""distance"": 1290}",a3e91e80-9b8d-4bd6-bbd7-011319e05a0c,107068 | 4455,a8ee9a3a-7714-46b6-a775-c184a9ccaa0a,"{""coordinates"": [9.33586, 47.41208], ""type"": ""...",1290.0,"47.41208, 9.33586",22:47:32,2023-11-30
876870,2023-11-30 22:47:33+00:00,"{""type"": ""reading"", ""distance"": 1569}",496ebab5-e27f-46a4-91bd-28e5086eb594,107108 | 0AEA,922b4584-2a83-405c-938f-9783c330c4ec,"{""coordinates"": [9.38204, 47.42595], ""type"": ""...",1569.0,"47.42595, 9.38204",22:47:33,2023-11-30
883052,2023-11-30 22:58:45+00:00,"{""type"": ""reading"", ""distance"": 1268}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,7d351916-a40c-4920-ac35-00bb78d99b97,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",1268.0,"47.40798, 9.33388",22:58:45,2023-11-30

In [64]:
# compiling a list of all ids without nan values present in their distance data
df["device_id"].value_counts()

non_nan_device_id_list = []
for i in df["device_id"].unique():
    non_nan_device_id_list.append(i)

non_nan_device_id_list

['e194deb4-afb0-4c83-aab2-71fcd13ca4e8',
 'eaea0bcc-2970-41e1-8821-29be122a65b0',
 '11d4bcfe-bde2-42bd-8ebc-43ee77012480',
 '8a6b6d27-9149-40ea-88b6-0c0d7446a0df',
 'a3e91e80-9b8d-4bd6-bbd7-011319e05a0c',
 'e3a7cfea-c281-46fe-8758-0bf2388181c0',
 '1607ca61-c966-483d-bbfb-d97027d507c1',
 'cfcfb74d-b13e-43fb-bc59-9eee4f6be818',
 '36816c9e-3b69-4b8c-b9f7-150b0edf94db',
 '96e70afa-3ce0-4674-a331-8b85aed97068',
 '2e4a8f6d-d398-4749-bc74-a24efa3f5644',
 '3301af3b-a6fe-429e-8b01-c7b71249abdf',
 'aae16e11-7f7e-4251-9e73-fd836db67b79',
 '134fc269-ec25-466f-82e7-780beb314108',
 '496ebab5-e27f-46a4-91bd-28e5086eb594',
 'b5b36857-0f47-4df9-8c8a-0ff431875b18',
 '7f9cad51-8a0c-4fa9-a6d4-8cf649d819ab',
 'b4d0f672-6436-483e-a0cd-fab4fe552a8c',
 '0b011106-e5fe-4202-92bd-c89abd042249',
 '5fe079a9-6e53-4a9d-b974-eca5d0916632',
 '79d9a5cb-3704-4a21-aedf-5989c70baed0',
 'e785cb18-96e1-4215-931a-82a731d2ee5a',
 '62ec2345-9665-4fd2-9fa7-91ead95dc99b']

In [65]:
# copying the list we created in the grÃ¼n_broken notebook into this notebook
nan_device_id_list = ['8a6b6d27-9149-40ea-88b6-0c0d7446a0df',
 'eaea0bcc-2970-41e1-8821-29be122a65b0',
 'cfcfb74d-b13e-43fb-bc59-9eee4f6be818',
 '62ec2345-9665-4fd2-9fa7-91ead95dc99b',
 '3301af3b-a6fe-429e-8b01-c7b71249abdf',
 '11d4bcfe-bde2-42bd-8ebc-43ee77012480',
 'e785cb18-96e1-4215-931a-82a731d2ee5a',
 '36816c9e-3b69-4b8c-b9f7-150b0edf94db',
 'b4d0f672-6436-483e-a0cd-fab4fe552a8c',
 '2e4a8f6d-d398-4749-bc74-a24efa3f5644',
 '5fe079a9-6e53-4a9d-b974-eca5d0916632',
 '0b011106-e5fe-4202-92bd-c89abd042249',
 'aae16e11-7f7e-4251-9e73-fd836db67b79',
 'b5b36857-0f47-4df9-8c8a-0ff431875b18',
 '7f9cad51-8a0c-4fa9-a6d4-8cf649d819ab',
 '496ebab5-e27f-46a4-91bd-28e5086eb594',
 '96e70afa-3ce0-4674-a331-8b85aed97068',
 '134fc269-ec25-466f-82e7-780beb314108',
 '1607ca61-c966-483d-bbfb-d97027d507c1',
 '79d9a5cb-3704-4a21-aedf-5989c70baed0',
 'a3e91e80-9b8d-4bd6-bbd7-011319e05a0c',
 'e3a7cfea-c281-46fe-8758-0bf2388181c0',
 'e194deb4-afb0-4c83-aab2-71fcd13ca4e8',
 'a82a9f13-4ec0-45bd-a218-4e2cc4ca11bb',
 'f97fcfd4-a7a8-4839-958a-334d8c02566c']

In [66]:
# Convert lists to sets for easier set operations
set1 = set(non_nan_device_id_list)
set2 = set(nan_device_id_list)

# List for common elements
common_elements = list(set1.intersection(set2))

# List for elements only in the first list
only_in_non_nan = list(set1.difference(set2))

# List for elements only in the second list
only_in_nan = list(set2.difference(set1))

# Print the results
print("Common elements:", common_elements)
print("Elements only in the non_nan list:", only_in_non_nan)
print("Elements only in the nan list:", only_in_nan)

Common elements: ['b4d0f672-6436-483e-a0cd-fab4fe552a8c', 'e785cb18-96e1-4215-931a-82a731d2ee5a', 'eaea0bcc-2970-41e1-8821-29be122a65b0', 'a3e91e80-9b8d-4bd6-bbd7-011319e05a0c', '5fe079a9-6e53-4a9d-b974-eca5d0916632', 'cfcfb74d-b13e-43fb-bc59-9eee4f6be818', '1607ca61-c966-483d-bbfb-d97027d507c1', 'aae16e11-7f7e-4251-9e73-fd836db67b79', 'e194deb4-afb0-4c83-aab2-71fcd13ca4e8', '2e4a8f6d-d398-4749-bc74-a24efa3f5644', 'e3a7cfea-c281-46fe-8758-0bf2388181c0', '79d9a5cb-3704-4a21-aedf-5989c70baed0', '96e70afa-3ce0-4674-a331-8b85aed97068', '3301af3b-a6fe-429e-8b01-c7b71249abdf', '62ec2345-9665-4fd2-9fa7-91ead95dc99b', '11d4bcfe-bde2-42bd-8ebc-43ee77012480', '36816c9e-3b69-4b8c-b9f7-150b0edf94db', '134fc269-ec25-466f-82e7-780beb314108', 'b5b36857-0f47-4df9-8c8a-0ff431875b18', '7f9cad51-8a0c-4fa9-a6d4-8cf649d819ab', '0b011106-e5fe-4202-92bd-c89abd042249', '8a6b6d27-9149-40ea-88b6-0c0d7446a0df', '496ebab5-e27f-46a4-91bd-28e5086eb594']
Elements only in the non_nan list: []
Elements only in the nan list: ['a82a9f13-4ec0-45bd-a218-4e2cc4ca11bb', 'f97fcfd4-a7a8-4839-958a-334d8c02566c']

In [67]:
# this id only consists of nan values
df.loc[df["device_id"] == "f97fcfd4-a7a8-4839-958a-334d8c02566c"]

Empty DataFrame
Columns: [measured_at, data, device_id, name, id, location, data_distance, geo_point_2d, time_uct, date_uct]
Index: []

In [68]:
# this id only consists of nan values
df.loc[df["device_id"] == "a82a9f13-4ec0-45bd-a218-4e2cc4ca11bb"]

Empty DataFrame
Columns: [measured_at, data, device_id, name, id, location, data_distance, geo_point_2d, time_uct, date_uct]
Index: []

In [69]:
# percentage NaN values for total df
(892933 - 800878) / 892933

0.10309284123220891

In [70]:
# calculation of nan % for all ids

df = pd.read_csv("./fuellstandsensoren-glassammelstellen-gruenglas.csv", sep = ";")

# Create a list of device_ids
device_ids = nan_device_id_list  # Replace with your actual device_ids


# Step 3: Loop through each device_id
for device_id in device_ids:
    # Filter the DataFrame for the current device_id
    device_df = df.loc[df['device_id'] == device_id]

    # Calculate the number of rows before dropping NaN values
    rows_before = len(device_df)

    # Calculate the number of rows after dropping NaN values
    rows_after = len(device_df.dropna())

    # Step 4: Calculate the percentage of NaN values
    percentage_nan = ((rows_before - rows_after) / rows_before) * 100

    # Print the results
    print(f"For device_id {device_id}:")
    print(f"  Rows before dropping NaN values: {rows_before}")
    print(f"  Rows after dropping NaN values: {rows_after}")
    print(f"  Percentage of NaN values: {percentage_nan:.2f}%")
    print()

For device_id 8a6b6d27-9149-40ea-88b6-0c0d7446a0df:
  Rows before dropping NaN values: 26845
  Rows after dropping NaN values: 26238
  Percentage of NaN values: 2.26%

For device_id eaea0bcc-2970-41e1-8821-29be122a65b0:
  Rows before dropping NaN values: 33475
  Rows after dropping NaN values: 32736
  Percentage of NaN values: 2.21%

For device_id cfcfb74d-b13e-43fb-bc59-9eee4f6be818:
  Rows before dropping NaN values: 59374
  Rows after dropping NaN values: 50166
  Percentage of NaN values: 15.51%

For device_id 62ec2345-9665-4fd2-9fa7-91ead95dc99b:
  Rows before dropping NaN values: 48507
  Rows after dropping NaN values: 40180
  Percentage of NaN values: 17.17%

For device_id 3301af3b-a6fe-429e-8b01-c7b71249abdf:
  Rows before dropping NaN values: 31413
  Rows after dropping NaN values: 30718
  Percentage of NaN values: 2.21%

For device_id 11d4bcfe-bde2-42bd-8ebc-43ee77012480:
  Rows before dropping NaN values: 38031
  Rows after dropping NaN values: 29493
  Percentage of NaN values: 22.45%

For device_id e785cb18-96e1-4215-931a-82a731d2ee5a:
  Rows before dropping NaN values: 24828
  Rows after dropping NaN values: 24268
  Percentage of NaN values: 2.26%

For device_id 36816c9e-3b69-4b8c-b9f7-150b0edf94db:
  Rows before dropping NaN values: 38605
  Rows after dropping NaN values: 29824
  Percentage of NaN values: 22.75%

For device_id b4d0f672-6436-483e-a0cd-fab4fe552a8c:
  Rows before dropping NaN values: 54246
  Rows after dropping NaN values: 52894
  Percentage of NaN values: 2.49%

For device_id 2e4a8f6d-d398-4749-bc74-a24efa3f5644:
  Rows before dropping NaN values: 56903
  Rows after dropping NaN values: 47547
  Percentage of NaN values: 16.44%

For device_id 5fe079a9-6e53-4a9d-b974-eca5d0916632:
  Rows before dropping NaN values: 41100
  Rows after dropping NaN values: 40184
  Percentage of NaN values: 2.23%

For device_id 0b011106-e5fe-4202-92bd-c89abd042249:
  Rows before dropping NaN values: 21808
  Rows after dropping NaN values: 21333
  Percentage of NaN values: 2.18%

For device_id aae16e11-7f7e-4251-9e73-fd836db67b79:
  Rows before dropping NaN values: 60974
  Rows after dropping NaN values: 59607
  Percentage of NaN values: 2.24%

For device_id b5b36857-0f47-4df9-8c8a-0ff431875b18:
  Rows before dropping NaN values: 21044
  Rows after dropping NaN values: 12614
  Percentage of NaN values: 40.06%

For device_id 7f9cad51-8a0c-4fa9-a6d4-8cf649d819ab:
  Rows before dropping NaN values: 59979
  Rows after dropping NaN values: 58640
  Percentage of NaN values: 2.23%

For device_id 496ebab5-e27f-46a4-91bd-28e5086eb594:
  Rows before dropping NaN values: 56182
  Rows after dropping NaN values: 54934
  Percentage of NaN values: 2.22%

For device_id 96e70afa-3ce0-4674-a331-8b85aed97068:
  Rows before dropping NaN values: 65862
  Rows after dropping NaN values: 56450
  Percentage of NaN values: 14.29%

For device_id 134fc269-ec25-466f-82e7-780beb314108:
  Rows before dropping NaN values: 55925
  Rows after dropping NaN values: 54645
  Percentage of NaN values: 2.29%

For device_id 1607ca61-c966-483d-bbfb-d97027d507c1:
  Rows before dropping NaN values: 12692
  Rows after dropping NaN values: 12403
  Percentage of NaN values: 2.28%

For device_id 79d9a5cb-3704-4a21-aedf-5989c70baed0:
  Rows before dropping NaN values: 8446
  Rows after dropping NaN values: 8263
  Percentage of NaN values: 2.17%

For device_id a3e91e80-9b8d-4bd6-bbd7-011319e05a0c:
  Rows before dropping NaN values: 56200
  Rows after dropping NaN values: 54834
  Percentage of NaN values: 2.43%

For device_id e3a7cfea-c281-46fe-8758-0bf2388181c0:
  Rows before dropping NaN values: 808
  Rows after dropping NaN values: 791
  Percentage of NaN values: 2.10%

For device_id e194deb4-afb0-4c83-aab2-71fcd13ca4e8:
  Rows before dropping NaN values: 9915
  Rows after dropping NaN values: 2116
  Percentage of NaN values: 78.66%

For device_id a82a9f13-4ec0-45bd-a218-4e2cc4ca11bb:
  Rows before dropping NaN values: 4645
  Rows after dropping NaN values: 0
  Percentage of NaN values: 100.00%

For device_id f97fcfd4-a7a8-4839-958a-334d8c02566c:
  Rows before dropping NaN values: 5126
  Rows after dropping NaN values: 0
  Percentage of NaN values: 100.00%