In [16]:
#%pip install pandas

In [1]:
# Import data for Weissglas
import pandas as pd
df = pd.read_csv("weissglas.csv", sep = ";")
df

,measured_at,data,device_id,name,id,location,data_distance,geo_point_2d
0,2021-04-10T00:51:05+02:00,"{""type"": ""reading"", ""distance"": 1268}",ecadcf7b-cf9e-477c-a56d-99d9472c4072,107040 | 8572,e57fc18f-dc47-42ff-a2c4-56d3f5ec6c43,"{""coordinates"": [9.382737711145921, 47.4153817...",1268.0,"47.41538175615662, 9.382737711145921"
1,2021-04-10T00:46:06+02:00,"{""type"": ""reading"", ""distance"": 946}",d4a9fa6b-880c-4d5d-9650-dff9f10c8a5f,107062 | 49A3,48f6185f-9d12-4410-9f54-f46ab1a9121a,"{""coordinates"": [9.346404926287022, 47.4196294...",946.0,"47.41962947506508, 9.346404926287022"
2,2021-04-10T00:28:26+02:00,"{""type"": ""reading"", ""distance"": 1397}",18def07f-6077-4543-a572-982cd63ef262,107058 | 282C,63657423-10da-4868-82b1-6881d67956ae,"{""coordinates"": [9.39318666070588, 47.42537272...",1397.0,"47.42537272354605, 9.39318666070588"
3,2021-04-10T00:24:52+02:00,"{""type"": ""reading"", ""distance"": 1462}",2a508d99-73fc-4992-8de0-f452a979f047,107095 | 64BC,ba25912a-7022-4ac3-bf2e-583b25255870,"{""coordinates"": [9.391682378992527, 47.4350966...",1462.0,"47.43509660210216, 9.391682378992527"
4,2021-04-10T00:23:24+02:00,"{""type"": ""reading"", ""distance"": 1268}",a7bbd831-d444-4011-b6df-37b47b8e218d,104244,b8d0c7fa-655a-44c3-bcea-70a8d22380db,"{""coordinates"": [9.373975357061, 47.4269863404...",1268.0,"47.42698634048571, 9.373975357061"
...,...,...,...,...,...,...,...,...
829561,2023-11-23T12:16:17+01:00,"{""type"": ""reading"", ""distance"": 1204}",827fd8d9-b94a-414c-aa38-0bb6d7880527,107047 | 0D1A,bfbc3c88-191e-4ab8-b176-47bf8c45cb0e,"{""coordinates"": [9.406626586373676, 47.4391951...",1204.0,"47.439195139754474, 9.406626586373676"
829562,2023-11-23T11:56:41+01:00,"{""type"": ""reading"", ""distance"": 817}",632c0d31-1145-49b7-b327-952ab64369d2,107065 | 4A3D,50b6ee6b-99a6-4197-9e94-95081a4767cc,"{""coordinates"": [9.33352525794038, 47.40792974...",817.0,"47.40792974774064, 9.33352525794038"
829563,2023-11-23T11:41:54+01:00,"{""type"": ""reading"", ""distance"": 881}",a1f343aa-dbbd-4b7e-ac42-58ee4bfffd06,107049 | 4B00,30444158-e7b2-4e1f-a2b7-7e26dc5d66f3,"{""coordinates"": [9.406667805210304, 47.4391990...",881.0,"47.43919901794274, 9.406667805210304"
829564,2023-11-23T10:50:36+01:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.251}",2a508d99-73fc-4992-8de0-f452a979f047,107095 | 64BC,7f994080-3cb6-4178-9a1b-9866fdb6e4f3,"{""coordinates"": [9.391682378992527, 47.4350966...",NaN,"47.43509660210216, 9.391682378992527"
829565,2023-11-23T10:48:09+01:00,"{""type"": ""reading"", ""distance"": 1311}",6d43f154-1009-470a-95a2-f40fe4b8a204,107072 | F389,abb8392f-2daa-42da-93c2-4aa3a0239a5c,"{""coordinates"": [9.33591068841119, 47.41209608...",1311.0,"47.41209608066285, 9.33591068841119"

In [6]:
df = pd.read_csv("weissglas.csv", sep = ";")

# Get all rows with nan data distance values:
nan_distance = df.loc[df["data_distance"].isna()].copy()

# Compile Device ids in a list:
nan_device_id_list = []
for i in nan_distance["device_id"].unique():
    nan_device_id_list.append(i)

nan_device_id_list

['ea6180ea-e2e3-476e-8e87-c1ae0abb504f',
 '632c0d31-1145-49b7-b327-952ab64369d2',
 '69715520-6a46-417c-9e78-7e71e90389d7',
 '2e98f08e-3cfb-4594-9f9c-133fab16f7ca',
 '6d43f154-1009-470a-95a2-f40fe4b8a204',
 '18def07f-6077-4543-a572-982cd63ef262',
 'a1f343aa-dbbd-4b7e-ac42-58ee4bfffd06',
 '2e7c7f54-ff9c-4464-a1aa-d247d30333db',
 '2a508d99-73fc-4992-8de0-f452a979f047',
 '827fd8d9-b94a-414c-aa38-0bb6d7880527',
 'a7bbd831-d444-4011-b6df-37b47b8e218d',
 'd4a9fa6b-880c-4d5d-9650-dff9f10c8a5f',
 'ecadcf7b-cf9e-477c-a56d-99d9472c4072',
 'f2aaa75a-0ea0-4e4a-8363-7c7a98c160d9',
 '7d1d7a97-2d16-4ccd-aae6-5cf8ffc2afb7',
 '8ddb5dd3-0822-485e-aebb-973df12c9dc9',
 '8d2aba9c-3983-4227-a8ff-eac6143ee60e',
 'a54a033f-6571-4319-adfe-52e6916be435',
 '195f9fb4-4486-4b3d-bb41-8a9d7715a931',
 'e92be93e-2221-4d7f-bd29-0177c7608c88',
 '286bb721-9cb2-448a-9c2f-aadd4a1bf2d6']

In [7]:
# Get rid of all nans
df = df.dropna()
df

,measured_at,data,device_id,name,id,location,data_distance,geo_point_2d
0,2021-04-10T00:51:05+02:00,"{""type"": ""reading"", ""distance"": 1268}",ecadcf7b-cf9e-477c-a56d-99d9472c4072,107040 | 8572,e57fc18f-dc47-42ff-a2c4-56d3f5ec6c43,"{""coordinates"": [9.382737711145921, 47.4153817...",1268.0,"47.41538175615662, 9.382737711145921"
1,2021-04-10T00:46:06+02:00,"{""type"": ""reading"", ""distance"": 946}",d4a9fa6b-880c-4d5d-9650-dff9f10c8a5f,107062 | 49A3,48f6185f-9d12-4410-9f54-f46ab1a9121a,"{""coordinates"": [9.346404926287022, 47.4196294...",946.0,"47.41962947506508, 9.346404926287022"
2,2021-04-10T00:28:26+02:00,"{""type"": ""reading"", ""distance"": 1397}",18def07f-6077-4543-a572-982cd63ef262,107058 | 282C,63657423-10da-4868-82b1-6881d67956ae,"{""coordinates"": [9.39318666070588, 47.42537272...",1397.0,"47.42537272354605, 9.39318666070588"
3,2021-04-10T00:24:52+02:00,"{""type"": ""reading"", ""distance"": 1462}",2a508d99-73fc-4992-8de0-f452a979f047,107095 | 64BC,ba25912a-7022-4ac3-bf2e-583b25255870,"{""coordinates"": [9.391682378992527, 47.4350966...",1462.0,"47.43509660210216, 9.391682378992527"
4,2021-04-10T00:23:24+02:00,"{""type"": ""reading"", ""distance"": 1268}",a7bbd831-d444-4011-b6df-37b47b8e218d,104244,b8d0c7fa-655a-44c3-bcea-70a8d22380db,"{""coordinates"": [9.373975357061, 47.4269863404...",1268.0,"47.42698634048571, 9.373975357061"
...,...,...,...,...,...,...,...,...
829560,2023-11-23T12:56:40+01:00,"{""type"": ""reading"", ""distance"": 817}",632c0d31-1145-49b7-b327-952ab64369d2,107065 | 4A3D,a156a1a0-5d7b-4f75-bec6-28f1948d3aa2,"{""coordinates"": [9.33352525794038, 47.40792974...",817.0,"47.40792974774064, 9.33352525794038"
829561,2023-11-23T12:16:17+01:00,"{""type"": ""reading"", ""distance"": 1204}",827fd8d9-b94a-414c-aa38-0bb6d7880527,107047 | 0D1A,bfbc3c88-191e-4ab8-b176-47bf8c45cb0e,"{""coordinates"": [9.406626586373676, 47.4391951...",1204.0,"47.439195139754474, 9.406626586373676"
829562,2023-11-23T11:56:41+01:00,"{""type"": ""reading"", ""distance"": 817}",632c0d31-1145-49b7-b327-952ab64369d2,107065 | 4A3D,50b6ee6b-99a6-4197-9e94-95081a4767cc,"{""coordinates"": [9.33352525794038, 47.40792974...",817.0,"47.40792974774064, 9.33352525794038"
829563,2023-11-23T11:41:54+01:00,"{""type"": ""reading"", ""distance"": 881}",a1f343aa-dbbd-4b7e-ac42-58ee4bfffd06,107049 | 4B00,30444158-e7b2-4e1f-a2b7-7e26dc5d66f3,"{""coordinates"": [9.406667805210304, 47.4391990...",881.0,"47.43919901794274, 9.406667805210304"
829565,2023-11-23T10:48:09+01:00,"{""type"": ""reading"", ""distance"": 1311}",6d43f154-1009-470a-95a2-f40fe4b8a204,107072 | F389,abb8392f-2daa-42da-93c2-4aa3a0239a5c,"{""coordinates"": [9.33591068841119, 47.41209608...",1311.0,"47.41209608066285, 9.33591068841119"

In [6]:
# Compiling list of all ids without nan values present in their distance data:
df["device_id"].value_counts()

non_nan_device_id_list = []
for i in df["device_id"].unique():
    non_nan_device_id_list.append(i)

non_nan_device_id_list

['ecadcf7b-cf9e-477c-a56d-99d9472c4072',
 'd4a9fa6b-880c-4d5d-9650-dff9f10c8a5f',
 '18def07f-6077-4543-a572-982cd63ef262',
 '2a508d99-73fc-4992-8de0-f452a979f047',
 'a7bbd831-d444-4011-b6df-37b47b8e218d',
 '632c0d31-1145-49b7-b327-952ab64369d2',
 '2e7c7f54-ff9c-4464-a1aa-d247d30333db',
 '827fd8d9-b94a-414c-aa38-0bb6d7880527',
 '8d2aba9c-3983-4227-a8ff-eac6143ee60e',
 'a54a033f-6571-4319-adfe-52e6916be435',
 'a1f343aa-dbbd-4b7e-ac42-58ee4bfffd06',
 'ea6180ea-e2e3-476e-8e87-c1ae0abb504f',
 '2e98f08e-3cfb-4594-9f9c-133fab16f7ca',
 '69715520-6a46-417c-9e78-7e71e90389d7',
 '6d43f154-1009-470a-95a2-f40fe4b8a204',
 'f2aaa75a-0ea0-4e4a-8363-7c7a98c160d9',
 '7d1d7a97-2d16-4ccd-aae6-5cf8ffc2afb7',
 '8ddb5dd3-0822-485e-aebb-973df12c9dc9',
 '195f9fb4-4486-4b3d-bb41-8a9d7715a931',
 'e92be93e-2221-4d7f-bd29-0177c7608c88',
 '286bb721-9cb2-448a-9c2f-aadd4a1bf2d6']

In [9]:
# Copying list we created above into this code part:
nan_device_id_list = ['ea6180ea-e2e3-476e-8e87-c1ae0abb504f',
 '632c0d31-1145-49b7-b327-952ab64369d2',
 '69715520-6a46-417c-9e78-7e71e90389d7',
 '2e98f08e-3cfb-4594-9f9c-133fab16f7ca',
 '6d43f154-1009-470a-95a2-f40fe4b8a204',
 '18def07f-6077-4543-a572-982cd63ef262',
 'a1f343aa-dbbd-4b7e-ac42-58ee4bfffd06',
 '2e7c7f54-ff9c-4464-a1aa-d247d30333db',
 '2a508d99-73fc-4992-8de0-f452a979f047',
 '827fd8d9-b94a-414c-aa38-0bb6d7880527',
 'a7bbd831-d444-4011-b6df-37b47b8e218d',
 'd4a9fa6b-880c-4d5d-9650-dff9f10c8a5f',
 'ecadcf7b-cf9e-477c-a56d-99d9472c4072',
 'f2aaa75a-0ea0-4e4a-8363-7c7a98c160d9',
 '7d1d7a97-2d16-4ccd-aae6-5cf8ffc2afb7',
 '8ddb5dd3-0822-485e-aebb-973df12c9dc9',
 '8d2aba9c-3983-4227-a8ff-eac6143ee60e',
 'a54a033f-6571-4319-adfe-52e6916be435',
 '195f9fb4-4486-4b3d-bb41-8a9d7715a931',
 'e92be93e-2221-4d7f-bd29-0177c7608c88',
 '286bb721-9cb2-448a-9c2f-aadd4a1bf2d6']

In [10]:
# Convert lists to sets for easier set operations:
set1 = set(non_nan_device_id_list)
set2 = set(nan_device_id_list)

# List for common elements:
common_elements = list(set1.intersection(set2))

# List for elements only in the first list:
only_in_non_nan = list(set1.difference(set2))

# List for elements only in the second list:
only_in_nan = list(set2.difference(set1))

# Print results:
print("Common elements:", common_elements)
print("Elements only in the non_nan list:", only_in_non_nan)
print("Elements only in the nan list:", only_in_nan)

Common elements: ['a1f343aa-dbbd-4b7e-ac42-58ee4bfffd06', 'ecadcf7b-cf9e-477c-a56d-99d9472c4072', '2e98f08e-3cfb-4594-9f9c-133fab16f7ca', '18def07f-6077-4543-a572-982cd63ef262', 'd4a9fa6b-880c-4d5d-9650-dff9f10c8a5f', '286bb721-9cb2-448a-9c2f-aadd4a1bf2d6', '8d2aba9c-3983-4227-a8ff-eac6143ee60e', 'a7bbd831-d444-4011-b6df-37b47b8e218d', 'a54a033f-6571-4319-adfe-52e6916be435', '632c0d31-1145-49b7-b327-952ab64369d2', 'f2aaa75a-0ea0-4e4a-8363-7c7a98c160d9', '2a508d99-73fc-4992-8de0-f452a979f047', '7d1d7a97-2d16-4ccd-aae6-5cf8ffc2afb7', '2e7c7f54-ff9c-4464-a1aa-d247d30333db', '6d43f154-1009-470a-95a2-f40fe4b8a204', '827fd8d9-b94a-414c-aa38-0bb6d7880527', '8ddb5dd3-0822-485e-aebb-973df12c9dc9', 'ea6180ea-e2e3-476e-8e87-c1ae0abb504f', '69715520-6a46-417c-9e78-7e71e90389d7', '195f9fb4-4486-4b3d-bb41-8a9d7715a931']
Elements only in the non_nan list: []
Elements only in the nan list: ['e92be93e-2221-4d7f-bd29-0177c7608c88']

In [7]:
import pandas as pd

# Calculation of nan % for all ids:
df = pd.read_csv("weissglas.csv", sep = ";")

nan_distance = df.loc[df["data_distance"].isna()].copy()

nan_device_id_list = []
for i in nan_distance["device_id"].unique():
    nan_device_id_list.append(i)

nan_device_id_list

# Create list of device_ids:
device_ids = nan_device_id_list # Replace with your actual device_ids


# Step 3: Loop through each device_id:
for device_id in device_ids:
    # Filter the DataFrame for the current device_id:
    device_df = df.loc[df['device_id'] == device_id]

    # Calculate the number of rows before dropping NaN values:
    rows_before = len(device_df)

    # Calculate the number of rows after dropping NaN values:
    rows_after = len(device_df.dropna())

    # Step 4: Calculate the percentage of NaN values:
    percentage_nan = ((rows_before - rows_after) / rows_before) * 100

    # Print results:
    print(f"For device_id {device_id}:")
    print(f"  Rows before dropping NaN values: {rows_before}")
    print(f"  Rows after dropping NaN values: {rows_after}")
    print(f"  Percentage of NaN values: {percentage_nan:.2f}%")
    print("")

For device_id ea6180ea-e2e3-476e-8e87-c1ae0abb504f:
  Rows before dropping NaN values: 41080
  Rows after dropping NaN values: 32571
  Percentage of NaN values: 20.71%

For device_id 632c0d31-1145-49b7-b327-952ab64369d2:
  Rows before dropping NaN values: 65970
  Rows after dropping NaN values: 56492
  Percentage of NaN values: 14.37%

For device_id 69715520-6a46-417c-9e78-7e71e90389d7:
  Rows before dropping NaN values: 23766
  Rows after dropping NaN values: 15577
  Percentage of NaN values: 34.46%

For device_id 2e98f08e-3cfb-4594-9f9c-133fab16f7ca:
  Rows before dropping NaN values: 22331
  Rows after dropping NaN values: 15055
  Percentage of NaN values: 32.58%

For device_id 6d43f154-1009-470a-95a2-f40fe4b8a204:
  Rows before dropping NaN values: 64655
  Rows after dropping NaN values: 55380
  Percentage of NaN values: 14.35%

For device_id 18def07f-6077-4543-a572-982cd63ef262:
  Rows before dropping NaN values: 67982
  Rows after dropping NaN values: 58427
  Percentage of NaN values: 14.06%

For device_id a1f343aa-dbbd-4b7e-ac42-58ee4bfffd06:
  Rows before dropping NaN values: 66739
  Rows after dropping NaN values: 57321
  Percentage of NaN values: 14.11%

For device_id 2e7c7f54-ff9c-4464-a1aa-d247d30333db:
  Rows before dropping NaN values: 20120
  Rows after dropping NaN values: 11926
  Percentage of NaN values: 40.73%

For device_id 2a508d99-73fc-4992-8de0-f452a979f047:
  Rows before dropping NaN values: 65181
  Rows after dropping NaN values: 56076
  Percentage of NaN values: 13.97%

For device_id 827fd8d9-b94a-414c-aa38-0bb6d7880527:
  Rows before dropping NaN values: 67581
  Rows after dropping NaN values: 58079
  Percentage of NaN values: 14.06%

For device_id a7bbd831-d444-4011-b6df-37b47b8e218d:
  Rows before dropping NaN values: 47979
  Rows after dropping NaN values: 39150
  Percentage of NaN values: 18.40%

For device_id d4a9fa6b-880c-4d5d-9650-dff9f10c8a5f:
  Rows before dropping NaN values: 37676
  Rows after dropping NaN values: 29621
  Percentage of NaN values: 21.38%

For device_id ecadcf7b-cf9e-477c-a56d-99d9472c4072:
  Rows before dropping NaN values: 64308
  Rows after dropping NaN values: 54719
  Percentage of NaN values: 14.91%

For device_id f2aaa75a-0ea0-4e4a-8363-7c7a98c160d9:
  Rows before dropping NaN values: 20496
  Rows after dropping NaN values: 12425
  Percentage of NaN values: 39.38%

For device_id 7d1d7a97-2d16-4ccd-aae6-5cf8ffc2afb7:
  Rows before dropping NaN values: 48155
  Rows after dropping NaN values: 39102
  Percentage of NaN values: 18.80%

For device_id 8ddb5dd3-0822-485e-aebb-973df12c9dc9:
  Rows before dropping NaN values: 20371
  Rows after dropping NaN values: 12140
  Percentage of NaN values: 40.41%

For device_id 8d2aba9c-3983-4227-a8ff-eac6143ee60e:
  Rows before dropping NaN values: 37474
  Rows after dropping NaN values: 28894
  Percentage of NaN values: 22.90%

For device_id a54a033f-6571-4319-adfe-52e6916be435:
  Rows before dropping NaN values: 31065
  Rows after dropping NaN values: 23309
  Percentage of NaN values: 24.97%

For device_id 195f9fb4-4486-4b3d-bb41-8a9d7715a931:
  Rows before dropping NaN values: 9414
  Rows after dropping NaN values: 1746
  Percentage of NaN values: 81.45%

For device_id e92be93e-2221-4d7f-bd29-0177c7608c88:
  Rows before dropping NaN values: 4310
  Rows after dropping NaN values: 0
  Percentage of NaN values: 100.00%

For device_id 286bb721-9cb2-448a-9c2f-aadd4a1bf2d6:
  Rows before dropping NaN values: 2913
  Rows after dropping NaN values: 1712
  Percentage of NaN values: 41.23%