In [24]:
# importing the data for grÃ¼nglas
import pandas as pd
df = pd.read_csv("./fuellstandsensoren-glassammelstellen-gruenglas.csv", sep = ";")
df

,measured_at,data,device_id,name,id,location,data_distance,geo_point_2d
0,2020-11-28T22:43:55+01:00,"{""type"": ""reading"", ""distance"": 838}",e785cb18-96e1-4215-931a-82a731d2ee5a,107096 | 4814,158c16a5-75c0-40e0-82aa-c976ef9660fb,"{""coordinates"": [9.39166, 47.43514], ""type"": ""...",838.0,"47.43514, 9.39166"
1,2020-11-28T22:43:22+01:00,"{""type"": ""reading"", ""distance"": 1548}",5fe079a9-6e53-4a9d-b974-eca5d0916632,107112 | 2B88,ee65bf04-fa7d-4ad9-a81f-47cd2a38e626,"{""coordinates"": [9.391704108835626, 47.4351514...",1548.0,"47.4351514110773, 9.391704108835626"
2,2020-11-28T22:40:56+01:00,"{""type"": ""reading"", ""distance"": 817}",b4d0f672-6436-483e-a0cd-fab4fe552a8c,104243,2d1a7e3f-ae62-4d64-9833-0b8000ad18e9,"{""coordinates"": [9.37393, 47.42701], ""type"": ""...",817.0,"47.42701, 9.37393"
3,2020-11-28T22:40:41+01:00,"{""type"": ""reading"", ""distance"": 2500}",b5b36857-0f47-4df9-8c8a-0ff431875b18,104246,ddd148a9-3762-4081-a16b-1c90cfe1e474,"{""coordinates"": [9.36637, 47.41634], ""type"": ""...",2500.0,"47.41634, 9.36637"
4,2020-11-28T22:38:19+01:00,"{""type"": ""reading"", ""distance"": 989}",7f9cad51-8a0c-4fa9-a6d4-8cf649d819ab,107048 | 671B,02b72973-e7b3-459c-81b5-f1f2f225b75a,"{""coordinates"": [9.38269, 47.41539], ""type"": ""...",989.0,"47.41539, 9.38269"
...,...,...,...,...,...,...,...,...
892928,2023-08-18T18:41:55+02:00,"{""type"": ""reading"", ""distance"": 1290}",aae16e11-7f7e-4251-9e73-fd836db67b79,107055 | 2C76,0dc78174-14d8-401a-baf1-1f57d634bab4,"{""coordinates"": [9.39314, 47.42541], ""type"": ""...",1290.0,"47.42541, 9.39314"
892929,2023-08-18T18:36:39+02:00,"{""type"": ""reading"", ""distance"": 1376}",cfcfb74d-b13e-43fb-bc59-9eee4f6be818,107038 | 2B8D,796b3fe0-641a-43e0-af6a-527a1ee9ae51,"{""coordinates"": [9.36611, 47.41086], ""type"": ""...",1376.0,"47.41086, 9.36611"
892930,2023-08-18T18:25:33+02:00,"{""type"": ""reading"", ""distance"": 1483}",496ebab5-e27f-46a4-91bd-28e5086eb594,107108 | 0AEA,134d1529-9637-4873-8047-65bdfbdbd50c,"{""coordinates"": [9.38204, 47.42595], ""type"": ""...",1483.0,"47.42595, 9.38204"
892931,2023-08-18T17:55:33+02:00,"{""type"": ""reading"", ""distance"": 1462}",496ebab5-e27f-46a4-91bd-28e5086eb594,107108 | 0AEA,141d9269-4601-4d84-ac78-7e4b13b6326a,"{""coordinates"": [9.38204, 47.42595], ""type"": ""...",1462.0,"47.42595, 9.38204"
892932,2023-08-18T17:41:55+02:00,"{""type"": ""reading"", ""distance"": 1247}",aae16e11-7f7e-4251-9e73-fd836db67b79,107055 | 2C76,64511fd0-381d-40a7-931b-dc1a327aa434,"{""coordinates"": [9.39314, 47.42541], ""type"": ""...",1247.0,"47.42541, 9.39314"

In [25]:
df.columns

Index(['measured_at', 'data', 'device_id', 'name', 'id', 'location',
       'data_distance', 'geo_point_2d'],
      dtype='object')

In [26]:
df.isna().sum()
# we need to know device id for NaN values

measured_at          0
data                 0
device_id            0
name                 0
id                   0
location             0
data_distance    92055
geo_point_2d         0
dtype: int64

In [27]:
# seeing how data_distance is distributed
df["data"].value_counts()

data
{"foo": 3}                                       73336
{"type": "reading", "distance": 2500}            42295
{"type": "reading", "distance": 1354}            21235
{"type": "reading", "distance": 1333}            20909
{"type": "reading", "distance": 516}             20769
                                                 ...
{"type": "inquiry", "battery_voltage": 2.605}        1
{"type": "inquiry", "battery_voltage": 3.282}        1
{"type": "reading", "distance": 2322}                1
{"type": "inquiry", "battery_voltage": 3.214}        1
{"type": "inquiry", "battery_voltage": 2.988}        1
Name: count, Length: 189, dtype: int64

In [28]:
df["data_distance"].value_counts()

data_distance
2500.0    42295
1354.0    21235
1333.0    20909
516.0     20769
1376.0    20544
          ...
2300.0        3
2171.0        2
2257.0        2
2322.0        1
2408.0        1
Name: count, Length: 98, dtype: int64

In [29]:
# getting all rows where there are nan data distance values
nan_distance = df.loc[df["data_distance"].isna()].copy()
nan_distance

,measured_at,data,device_id,name,id,location,data_distance,geo_point_2d
70,2020-11-28T14:23:42+01:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.46}",8a6b6d27-9149-40ea-88b6-0c0d7446a0df,107127 | 817E,c8a89283-0987-451e-b3e5-77551b2a185a,"{""coordinates"": [9.37681, 47.43724], ""type"": ""...",NaN,"47.43724, 9.37681"
84,2020-11-28T12:22:14+01:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.469}",eaea0bcc-2970-41e1-8821-29be122a65b0,107114 | 654B,c4199f93-ab10-475c-a6c1-c8fc0b054403,"{""coordinates"": [9.391743082129409, 47.4351625...",NaN,"47.4351625218373, 9.391743082129409"
105,2020-11-28T10:00:58+01:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.486}",cfcfb74d-b13e-43fb-bc59-9eee4f6be818,107038 | 2B8D,27c63614-2e4b-4d73-bcb4-538643e52919,"{""coordinates"": [9.36611, 47.41086], ""type"": ""...",NaN,"47.41086, 9.36611"
106,2020-11-28T09:47:22+01:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.426}",62ec2345-9665-4fd2-9fa7-91ead95dc99b,107031 | 6348,a144b973-59d7-41e3-9016-900ee716bad5,"{""coordinates"": [9.29952, 47.40395], ""type"": ""...",NaN,"47.40395, 9.29952"
266,2020-11-27T12:22:18+01:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.512}",eaea0bcc-2970-41e1-8821-29be122a65b0,107114 | 654B,2ebd923e-48fc-46d9-b3e4-7bf1849d61b0,"{""coordinates"": [9.391743082129409, 47.4351625...",NaN,"47.4351625218373, 9.391743082129409"
...,...,...,...,...,...,...,...,...
892783,2023-10-05T11:22:16+02:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.575}",a3e91e80-9b8d-4bd6-bbd7-011319e05a0c,107068 | 4455,27f363fe-99e3-4c0b-83f6-d073744e9384,"{""coordinates"": [9.33586, 47.41208], ""type"": ""...",NaN,"47.41208, 9.33586"
892855,2023-08-19T15:48:03+02:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.697}",b4d0f672-6436-483e-a0cd-fab4fe552a8c,104243,d5c5a698-4467-4001-857b-a0ca395c0c54,"{""coordinates"": [9.37393, 47.42701], ""type"": ""...",NaN,"47.42701, 9.37393"
892870,2023-08-19T11:26:41+02:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.64}",a3e91e80-9b8d-4bd6-bbd7-011319e05a0c,107068 | 4455,14065af0-4e4a-482d-b26d-5ba983176317,"{""coordinates"": [9.33586, 47.41208], ""type"": ""...",NaN,"47.41208, 9.33586"
892888,2023-08-19T06:38:06+02:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.548}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,04a21a25-5394-4b4b-98bf-7795ba6a9e26,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388"
892920,2023-08-18T22:24:15+02:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.668}",b4d0f672-6436-483e-a0cd-fab4fe552a8c,104243,2e8c04ef-709f-4015-8dbd-654e44eaabf7,"{""coordinates"": [9.37393, 47.42701], ""type"": ""...",NaN,"47.42701, 9.37393"

In [30]:
# seeing which device ids have nan values
nan_distance["device_id"].value_counts()#

device_id
96e70afa-3ce0-4674-a331-8b85aed97068    9412
2e4a8f6d-d398-4749-bc74-a24efa3f5644    9356
cfcfb74d-b13e-43fb-bc59-9eee4f6be818    9208
36816c9e-3b69-4b8c-b9f7-150b0edf94db    8781
11d4bcfe-bde2-42bd-8ebc-43ee77012480    8538
b5b36857-0f47-4df9-8c8a-0ff431875b18    8430
62ec2345-9665-4fd2-9fa7-91ead95dc99b    8327
e194deb4-afb0-4c83-aab2-71fcd13ca4e8    7799
f97fcfd4-a7a8-4839-958a-334d8c02566c    5126
a82a9f13-4ec0-45bd-a218-4e2cc4ca11bb    4645
aae16e11-7f7e-4251-9e73-fd836db67b79    1367
a3e91e80-9b8d-4bd6-bbd7-011319e05a0c    1366
b4d0f672-6436-483e-a0cd-fab4fe552a8c    1352
7f9cad51-8a0c-4fa9-a6d4-8cf649d819ab    1339
134fc269-ec25-466f-82e7-780beb314108    1280
496ebab5-e27f-46a4-91bd-28e5086eb594    1248
5fe079a9-6e53-4a9d-b974-eca5d0916632     916
eaea0bcc-2970-41e1-8821-29be122a65b0     739
3301af3b-a6fe-429e-8b01-c7b71249abdf     695
8a6b6d27-9149-40ea-88b6-0c0d7446a0df     607
e785cb18-96e1-4215-931a-82a731d2ee5a     560
0b011106-e5fe-4202-92bd-c89abd042249     475
1607ca61-c966-483d-bbfb-d97027d507c1     289
79d9a5cb-3704-4a21-aedf-5989c70baed0     183
e3a7cfea-c281-46fe-8758-0bf2388181c0      17
Name: count, dtype: int64

In [31]:
# compiling these device ids in a list
nan_device_id_list = []
for i in nan_distance["device_id"].unique():
    nan_device_id_list.append(i)

nan_device_id_list

['8a6b6d27-9149-40ea-88b6-0c0d7446a0df',
 'eaea0bcc-2970-41e1-8821-29be122a65b0',
 'cfcfb74d-b13e-43fb-bc59-9eee4f6be818',
 '62ec2345-9665-4fd2-9fa7-91ead95dc99b',
 '3301af3b-a6fe-429e-8b01-c7b71249abdf',
 '11d4bcfe-bde2-42bd-8ebc-43ee77012480',
 'e785cb18-96e1-4215-931a-82a731d2ee5a',
 '36816c9e-3b69-4b8c-b9f7-150b0edf94db',
 'b4d0f672-6436-483e-a0cd-fab4fe552a8c',
 '2e4a8f6d-d398-4749-bc74-a24efa3f5644',
 '5fe079a9-6e53-4a9d-b974-eca5d0916632',
 '0b011106-e5fe-4202-92bd-c89abd042249',
 'aae16e11-7f7e-4251-9e73-fd836db67b79',
 'b5b36857-0f47-4df9-8c8a-0ff431875b18',
 '7f9cad51-8a0c-4fa9-a6d4-8cf649d819ab',
 '496ebab5-e27f-46a4-91bd-28e5086eb594',
 '96e70afa-3ce0-4674-a331-8b85aed97068',
 '134fc269-ec25-466f-82e7-780beb314108',
 '1607ca61-c966-483d-bbfb-d97027d507c1',
 '79d9a5cb-3704-4a21-aedf-5989c70baed0',
 'a3e91e80-9b8d-4bd6-bbd7-011319e05a0c',
 'e3a7cfea-c281-46fe-8758-0bf2388181c0',
 'e194deb4-afb0-4c83-aab2-71fcd13ca4e8',
 'a82a9f13-4ec0-45bd-a218-4e2cc4ca11bb',
 'f97fcfd4-a7a8-4839-958a-334d8c02566c']

In [32]:
# ensuring a datetime format in uct
nan_distance["measured_at"] = pd.to_datetime(nan_distance["measured_at"], utc=True)
nan_distance

,measured_at,data,device_id,name,id,location,data_distance,geo_point_2d
70,2020-11-28 13:23:42+00:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.46}",8a6b6d27-9149-40ea-88b6-0c0d7446a0df,107127 | 817E,c8a89283-0987-451e-b3e5-77551b2a185a,"{""coordinates"": [9.37681, 47.43724], ""type"": ""...",NaN,"47.43724, 9.37681"
84,2020-11-28 11:22:14+00:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.469}",eaea0bcc-2970-41e1-8821-29be122a65b0,107114 | 654B,c4199f93-ab10-475c-a6c1-c8fc0b054403,"{""coordinates"": [9.391743082129409, 47.4351625...",NaN,"47.4351625218373, 9.391743082129409"
105,2020-11-28 09:00:58+00:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.486}",cfcfb74d-b13e-43fb-bc59-9eee4f6be818,107038 | 2B8D,27c63614-2e4b-4d73-bcb4-538643e52919,"{""coordinates"": [9.36611, 47.41086], ""type"": ""...",NaN,"47.41086, 9.36611"
106,2020-11-28 08:47:22+00:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.426}",62ec2345-9665-4fd2-9fa7-91ead95dc99b,107031 | 6348,a144b973-59d7-41e3-9016-900ee716bad5,"{""coordinates"": [9.29952, 47.40395], ""type"": ""...",NaN,"47.40395, 9.29952"
266,2020-11-27 11:22:18+00:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.512}",eaea0bcc-2970-41e1-8821-29be122a65b0,107114 | 654B,2ebd923e-48fc-46d9-b3e4-7bf1849d61b0,"{""coordinates"": [9.391743082129409, 47.4351625...",NaN,"47.4351625218373, 9.391743082129409"
...,...,...,...,...,...,...,...,...
892783,2023-10-05 09:22:16+00:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.575}",a3e91e80-9b8d-4bd6-bbd7-011319e05a0c,107068 | 4455,27f363fe-99e3-4c0b-83f6-d073744e9384,"{""coordinates"": [9.33586, 47.41208], ""type"": ""...",NaN,"47.41208, 9.33586"
892855,2023-08-19 13:48:03+00:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.697}",b4d0f672-6436-483e-a0cd-fab4fe552a8c,104243,d5c5a698-4467-4001-857b-a0ca395c0c54,"{""coordinates"": [9.37393, 47.42701], ""type"": ""...",NaN,"47.42701, 9.37393"
892870,2023-08-19 09:26:41+00:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.64}",a3e91e80-9b8d-4bd6-bbd7-011319e05a0c,107068 | 4455,14065af0-4e4a-482d-b26d-5ba983176317,"{""coordinates"": [9.33586, 47.41208], ""type"": ""...",NaN,"47.41208, 9.33586"
892888,2023-08-19 04:38:06+00:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.548}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,04a21a25-5394-4b4b-98bf-7795ba6a9e26,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388"
892920,2023-08-18 20:24:15+00:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.668}",b4d0f672-6436-483e-a0cd-fab4fe552a8c,104243,2e8c04ef-709f-4015-8dbd-654e44eaabf7,"{""coordinates"": [9.37393, 47.42701], ""type"": ""...",NaN,"47.42701, 9.37393"

In [33]:
# creating two new columns for better understanding
nan_distance["time_uct"] = nan_distance["measured_at"].dt.time
nan_distance["date_uct"] = nan_distance["measured_at"].dt.date
df_nan = nan_distance
df_nan

,measured_at,data,device_id,name,id,location,data_distance,geo_point_2d,time_uct,date_uct
70,2020-11-28 13:23:42+00:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.46}",8a6b6d27-9149-40ea-88b6-0c0d7446a0df,107127 | 817E,c8a89283-0987-451e-b3e5-77551b2a185a,"{""coordinates"": [9.37681, 47.43724], ""type"": ""...",NaN,"47.43724, 9.37681",13:23:42,2020-11-28
84,2020-11-28 11:22:14+00:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.469}",eaea0bcc-2970-41e1-8821-29be122a65b0,107114 | 654B,c4199f93-ab10-475c-a6c1-c8fc0b054403,"{""coordinates"": [9.391743082129409, 47.4351625...",NaN,"47.4351625218373, 9.391743082129409",11:22:14,2020-11-28
105,2020-11-28 09:00:58+00:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.486}",cfcfb74d-b13e-43fb-bc59-9eee4f6be818,107038 | 2B8D,27c63614-2e4b-4d73-bcb4-538643e52919,"{""coordinates"": [9.36611, 47.41086], ""type"": ""...",NaN,"47.41086, 9.36611",09:00:58,2020-11-28
106,2020-11-28 08:47:22+00:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.426}",62ec2345-9665-4fd2-9fa7-91ead95dc99b,107031 | 6348,a144b973-59d7-41e3-9016-900ee716bad5,"{""coordinates"": [9.29952, 47.40395], ""type"": ""...",NaN,"47.40395, 9.29952",08:47:22,2020-11-28
266,2020-11-27 11:22:18+00:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.512}",eaea0bcc-2970-41e1-8821-29be122a65b0,107114 | 654B,2ebd923e-48fc-46d9-b3e4-7bf1849d61b0,"{""coordinates"": [9.391743082129409, 47.4351625...",NaN,"47.4351625218373, 9.391743082129409",11:22:18,2020-11-27
...,...,...,...,...,...,...,...,...,...,...
892783,2023-10-05 09:22:16+00:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.575}",a3e91e80-9b8d-4bd6-bbd7-011319e05a0c,107068 | 4455,27f363fe-99e3-4c0b-83f6-d073744e9384,"{""coordinates"": [9.33586, 47.41208], ""type"": ""...",NaN,"47.41208, 9.33586",09:22:16,2023-10-05
892855,2023-08-19 13:48:03+00:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.697}",b4d0f672-6436-483e-a0cd-fab4fe552a8c,104243,d5c5a698-4467-4001-857b-a0ca395c0c54,"{""coordinates"": [9.37393, 47.42701], ""type"": ""...",NaN,"47.42701, 9.37393",13:48:03,2023-08-19
892870,2023-08-19 09:26:41+00:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.64}",a3e91e80-9b8d-4bd6-bbd7-011319e05a0c,107068 | 4455,14065af0-4e4a-482d-b26d-5ba983176317,"{""coordinates"": [9.33586, 47.41208], ""type"": ""...",NaN,"47.41208, 9.33586",09:26:41,2023-08-19
892888,2023-08-19 04:38:06+00:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.548}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,04a21a25-5394-4b4b-98bf-7795ba6a9e26,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388",04:38:06,2023-08-19
892920,2023-08-18 20:24:15+00:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.668}",b4d0f672-6436-483e-a0cd-fab4fe552a8c,104243,2e8c04ef-709f-4015-8dbd-654e44eaabf7,"{""coordinates"": [9.37393, 47.42701], ""type"": ""...",NaN,"47.42701, 9.37393",20:24:15,2023-08-18

In [34]:
# sorting the values in increasing time
df_nan.sort_values(by='measured_at', inplace=True)
df_nan

,measured_at,data,device_id,name,id,location,data_distance,geo_point_2d,time_uct,date_uct
690036,2020-01-01 00:01:03+00:00,"{""foo"": 3}",2e4a8f6d-d398-4749-bc74-a24efa3f5644,107123 | 980F,4e1f3cfc-e265-4bde-8500-36974fc5968a,"{""coordinates"": [9.36053, 47.42574], ""type"": ""...",NaN,"47.42574, 9.36053",00:01:03,2020-01-01
98089,2020-01-01 00:01:16+00:00,"{""foo"": 3}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,403f2bc4-f68a-4d6b-8ffc-ca64f693a8e9,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388",00:01:16,2020-01-01
406734,2020-01-01 00:03:19+00:00,"{""foo"": 3}",b5b36857-0f47-4df9-8c8a-0ff431875b18,104246,0b999403-5406-4344-b5ae-aa2525624f4b,"{""coordinates"": [9.36637, 47.41634], ""type"": ""...",NaN,"47.41634, 9.36637",00:03:19,2020-01-01
690035,2020-01-01 00:17:21+00:00,"{""foo"": 3}",62ec2345-9665-4fd2-9fa7-91ead95dc99b,107031 | 6348,40b7b7f0-3fc1-4d69-a33c-511bec6541af,"{""coordinates"": [9.29952, 47.40395], ""type"": ""...",NaN,"47.40395, 9.29952",00:17:21,2020-01-01
98087,2020-01-01 00:17:32+00:00,"{""foo"": 3}",a82a9f13-4ec0-45bd-a218-4e2cc4ca11bb,107070 | 454B,f6d0e6eb-9859-434d-8649-ba4eaa36aab8,"{""coordinates"": [9.338409956002408, 47.4078311...",NaN,"47.407831127695545, 9.338409956002408",00:17:32,2020-01-01
...,...,...,...,...,...,...,...,...,...,...
806134,2023-11-30 04:28:52+00:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.274}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,9e7227d6-95c1-4b49-907e-e3e0bcf7ac7a,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388",04:28:52,2023-11-30
668112,2023-11-30 08:36:30+00:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.282}",7f9cad51-8a0c-4fa9-a6d4-8cf649d819ab,107048 | 671B,834d0cd9-6404-42ef-b0f3-709add60ba57,"{""coordinates"": [9.38269, 47.41539], ""type"": ""...",NaN,"47.41539, 9.38269",08:36:30,2023-11-30
806116,2023-11-30 09:17:38+00:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.443}",a3e91e80-9b8d-4bd6-bbd7-011319e05a0c,107068 | 4455,77667c79-2fdc-4c99-a0d0-4210ebc08065,"{""coordinates"": [9.33586, 47.41208], ""type"": ""...",NaN,"47.41208, 9.33586",09:17:38,2023-11-30
806098,2023-11-30 12:17:38+00:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.313}",496ebab5-e27f-46a4-91bd-28e5086eb594,107108 | 0AEA,8a2b4228-ce75-4a44-aade-e5bfa05b3642,"{""coordinates"": [9.38204, 47.42595], ""type"": ""...",NaN,"47.42595, 9.38204",12:17:38,2023-11-30
883056,2023-11-30 21:02:51+00:00,"{""type"": ""inquiry"", ""battery_voltage"": 3.244}",aae16e11-7f7e-4251-9e73-fd836db67b79,107055 | 2C76,1a207c30-2820-4a68-a50a-602d5261c723,"{""coordinates"": [9.39314, 47.42541], ""type"": ""...",NaN,"47.42541, 9.39314",21:02:51,2023-11-30

In [35]:
# trying it out for a specific id
df96 = df_nan.loc[df_nan["device_id"] == "96e70afa-3ce0-4674-a331-8b85aed97068"].copy()
df96.head(20)

,measured_at,data,device_id,name,id,location,data_distance,geo_point_2d,time_uct,date_uct
98089,2020-01-01 00:01:16+00:00,"{""foo"": 3}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,403f2bc4-f68a-4d6b-8ffc-ca64f693a8e9,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388",00:01:16,2020-01-01
98085,2020-01-01 00:31:16+00:00,"{""foo"": 3}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,a4d79863-f06f-4bc1-afe5-051d6801b444,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388",00:31:16,2020-01-01
406726,2020-01-01 01:01:16+00:00,"{""foo"": 3}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,2c27b05e-3ab5-4fb3-9501-fd7f263a0d37,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388",01:01:16,2020-01-01
98069,2020-01-01 01:31:16+00:00,"{""foo"": 3}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,019d0a3b-2ad7-4d9c-baca-09bf70a92de8,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388",01:31:16,2020-01-01
98063,2020-01-01 02:01:16+00:00,"{""foo"": 3}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,35ae6396-2aff-48be-aed9-e33226757c31,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388",02:01:16,2020-01-01
98057,2020-01-01 02:31:16+00:00,"{""foo"": 3}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,a83190da-6e8e-4fec-ac37-acd8bfda2a88,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388",02:31:16,2020-01-01
759130,2020-01-01 03:01:16+00:00,"{""foo"": 3}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,01d7dc83-5fcd-458c-b98b-ad14b7af7283,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388",03:01:16,2020-01-01
384744,2020-01-01 03:31:16+00:00,"{""foo"": 3}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,e661cf9c-d542-44bd-af8f-37c4b83a560f,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388",03:31:16,2020-01-01
98049,2020-01-01 04:01:16+00:00,"{""foo"": 3}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,9b923e81-f80b-4d4c-b2e2-02746e10ebe3,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388",04:01:16,2020-01-01
384732,2020-01-01 04:31:16+00:00,"{""foo"": 3}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,35843bba-7bce-4742-a55f-4fcab489618e,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388",04:31:16,2020-01-01
690014,2020-01-01 05:01:15+00:00,"{""foo"": 3}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,bac6f5c4-901c-4bf6-9a7e-6369c6c21c2d,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388",05:01:15,2020-01-01
384717,2020-01-01 05:31:15+00:00,"{""foo"": 3}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,b2ce14bf-b0a9-44e9-92e3-37ee169bcab2,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388",05:31:15,2020-01-01
406688,2020-01-01 06:01:15+00:00,"{""foo"": 3}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,8874405b-fee6-477c-97f9-8869aa50ebd3,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388",06:01:15,2020-01-01
690008,2020-01-01 06:31:15+00:00,"{""foo"": 3}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,d95bfb70-caaa-4bbe-81ae-ca75c120bc2d,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388",06:31:15,2020-01-01
406682,2020-01-01 06:31:19+00:00,"{""foo"": 3}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,f189008e-a454-4a57-859e-6b84b849ad8f,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388",06:31:19,2020-01-01
98023,2020-01-01 07:01:15+00:00,"{""foo"": 3}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,2a2e5ae3-11c7-4d9f-b4cc-5230e339374e,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388",07:01:15,2020-01-01
384690,2020-01-01 07:31:15+00:00,"{""foo"": 3}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,22f1f70d-ebe6-44f0-86c3-0fca92fe4bce,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388",07:31:15,2020-01-01
98011,2020-01-01 08:01:15+00:00,"{""foo"": 3}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,0fc7ed2c-a1b0-4ced-9303-980642f106ef,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388",08:01:15,2020-01-01
384678,2020-01-01 08:31:15+00:00,"{""foo"": 3}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,45013e79-b170-49fe-81a3-c3e266e155c4,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388",08:31:15,2020-01-01
384672,2020-01-01 09:01:15+00:00,"{""foo"": 3}",96e70afa-3ce0-4674-a331-8b85aed97068,107077 | 2CC4,a8152b98-8c83-4e72-b266-124b5504f085,"{""coordinates"": [9.33388, 47.40798], ""type"": ""...",NaN,"47.40798, 9.33388",09:01:15,2020-01-01

In [36]:
# creating a custom function to inspect on which time segments nan values are present

from datetime import timedelta
def broken_time(df_device_id):
    global start_time, end_time, broken_list
    
    # Reset variables
    start_time = None
    end_time = None
    broken_list = []
    
    for i in df_device_id["date_uct"]:
        if start_time is None:
            # First timestamp
            start_time = i
            broken_list.append(f"Start Date: {start_time}")
            end_time = start_time
            
        # checking if the prior value = the value now    
        elif i == end_time:
            continue

        # checking if the prior value + 1 day = the value now   
        elif i == end_time + timedelta(days=1):
            end_time += timedelta(days=1)
        
        # checking if the prior value + 2 = the value now   
        elif i == end_time + timedelta(days=2):
            end_time += timedelta(days=2)

        else:
            broken_list.append(f"End Date: {end_time}")
        
            start_time = i
            broken_list.append(f"Start Date: {start_time}")
            end_time = start_time

    if end_time is not None:
        # End the last charge if applicable
        broken_list.append(f"End Date: {end_time}")

    return broken_list

broken_time(df96)

['Start Date: 2020-01-01',
 'End Date: 2020-10-08',
 'Start Date: 2020-10-11',
 'End Date: 2020-10-22',
 'Start Date: 2020-10-26',
 'End Date: 2020-11-19',
 'Start Date: 2020-11-22',
 'End Date: 2020-11-23',
 'Start Date: 2020-11-27',
 'End Date: 2022-01-28',
 'Start Date: 2022-01-31',
 'End Date: 2022-07-12',
 'Start Date: 2022-07-15',
 'End Date: 2023-01-18',
 'Start Date: 2023-01-21',
 'End Date: 2023-11-30']

In [37]:
# creating a custom function to that turns broken_list from the above function into a dataframe

from datetime import datetime
def broken_time_df(broken_list):
    data = {'Start Date': [], 'End Date': []}
    current_start_date = None

    for item in broken_list:
        # Split each item into its type (Start or End) and the date
        date_type, date_value = item.split(': ')
        date_value = datetime.strptime(date_value, '%Y-%m-%d').date()

        # Check if it's a Start Date or End Date and update the data dictionary
        if date_type == 'Start Date':
            current_start_date = date_value
        elif date_type == 'End Date':
            data['Start Date'].append(current_start_date)
            data['End Date'].append(date_value)

    # Create a DataFrame from the dictionary
    df = pd.DataFrame(data)
    return df
broken_time_df(broken_time(df96))

   Start Date    End Date
0  2020-01-01  2020-10-08
1  2020-10-11  2020-10-22
2  2020-10-26  2020-11-19
3  2020-11-22  2020-11-23
4  2020-11-27  2022-01-28
5  2022-01-31  2022-07-12
6  2022-07-15  2023-01-18
7  2023-01-21  2023-11-30

In [38]:
# Modifying the function to create a dataframe for each Device ID

import pandas as pd

def create_dataframes(main_df, column_name, list_of_values):
    # Create an empty dictionary to store DataFrames
    dfs = {}

    # Iterate through the list and create DataFrames
    for i, value in enumerate(list_of_values):
        # Create a new DataFrame based on the condition
        dfs[f'df_{i + 1}'] = main_df.loc[main_df[column_name] == value].copy()

    return dfs

result_dfs = create_dataframes(df_nan, 'device_id', nan_device_id_list)
result_dfs

{'df_1':                      measured_at  \
 644037 2020-06-17 13:37:39+00:00
 643832 2020-06-18 13:37:34+00:00
 454401 2020-06-19 13:37:28+00:00
 454082 2020-06-20 13:37:23+00:00
 50413  2020-06-21 13:37:18+00:00
 ...                          ...
 450932 2023-06-12 10:40:09+00:00
 450754 2023-06-13 10:40:04+00:00
 710424 2023-07-14 13:07:37+00:00
 874475 2023-07-14 13:07:40+00:00
 888458 2023-07-16 13:07:11+00:00

                                                      data  \
 644037      {"type": "inquiry", "battery_voltage": 3.584}
 643832      {"type": "inquiry", "battery_voltage": 3.649}
 454401      {"type": "inquiry", "battery_voltage": 3.566}
 454082       {"type": "inquiry", "battery_voltage": 3.64}
 50413        {"type": "inquiry", "battery_voltage": 3.63}
 ...                                                   ...
 450932      {"type": "inquiry", "battery_voltage": 3.584}
 450754      {"type": "inquiry", "battery_voltage": 3.584}
 710424  {"type": "inquiry", "firmware_type": "FWR-1010...
 874475      {"type": "inquiry", "battery_voltage": 3.575}
 888458      {"type": "inquiry", "battery_voltage": 3.575}

                                    device_id           name  \
 644037  8a6b6d27-9149-40ea-88b6-0c0d7446a0df  107127 | 817E
 643832  8a6b6d27-9149-40ea-88b6-0c0d7446a0df  107127 | 817E
 454401  8a6b6d27-9149-40ea-88b6-0c0d7446a0df  107127 | 817E
 454082  8a6b6d27-9149-40ea-88b6-0c0d7446a0df  107127 | 817E
 50413   8a6b6d27-9149-40ea-88b6-0c0d7446a0df  107127 | 817E
 ...                                      ...            ...
 450932  8a6b6d27-9149-40ea-88b6-0c0d7446a0df  107127 | 817E
 450754  8a6b6d27-9149-40ea-88b6-0c0d7446a0df  107127 | 817E
 710424  8a6b6d27-9149-40ea-88b6-0c0d7446a0df  107127 | 817E
 874475  8a6b6d27-9149-40ea-88b6-0c0d7446a0df  107127 | 817E
 888458  8a6b6d27-9149-40ea-88b6-0c0d7446a0df  107127 | 817E

                                           id  \
 644037  dad60c00-f9ed-44b9-a9ef-7901f2da2257
 643832  7fee7d58-369f-4241-b8f4-53b7feb8cebb
 454401  ffb4bfbd-8819-4457-8c09-2e33c64736b6
 454082  56d120e8-f901-4432-a67e-264631a56ec6
 50413   4b57b615-4b01-44a0-a401-74e63f7f4a13
 ...                                      ...
 450932  d2917d1e-3cf3-47ee-81dd-14662f7b280b
 450754  eb63b6cf-6a3c-43d9-9b8f-5e54cd881e37
 710424  46426007-c7a0-4595-8298-77d968b3e5d6
 874475  a14334ab-02f6-4d37-b2d3-4707d66ae93c
 888458  6ccb9cf4-d614-4c73-afb9-dfaa980a6672

                                                  location  data_distance  \
 644037  {"coordinates": [9.37681, 47.43724], "type": "...            NaN
 643832  {"coordinates": [9.37681, 47.43724], "type": "...            NaN
 454401  {"coordinates": [9.37681, 47.43724], "type": "...            NaN
 454082  {"coordinates": [9.37681, 47.43724], "type": "...            NaN
 50413   {"coordinates": [9.37681, 47.43724], "type": "...            NaN
 ...                                                   ...            ...
 450932  {"coordinates": [9.37681, 47.43724], "type": "...            NaN
 450754  {"coordinates": [9.37681, 47.43724], "type": "...            NaN
 710424  {"coordinates": [9.37681, 47.43724], "type": "...            NaN
 874475  {"coordinates": [9.37681, 47.43724], "type": "...            NaN
 888458  {"coordinates": [9.37681, 47.43724], "type": "...            NaN

              geo_point_2d  time_uct    date_uct
 644037  47.43724, 9.37681  13:37:39  2020-06-17
 643832  47.43724, 9.37681  13:37:34  2020-06-18
 454401  47.43724, 9.37681  13:37:28  2020-06-19
 454082  47.43724, 9.37681  13:37:23  2020-06-20
 50413   47.43724, 9.37681  13:37:18  2020-06-21
 ...                   ...       ...         ...
 450932  47.43724, 9.37681  10:40:09  2023-06-12
 450754  47.43724, 9.37681  10:40:04  2023-06-13
 710424  47.43724, 9.37681  13:07:37  2023-07-14
 874475  47.43724, 9.37681  13:07:40  2023-07-14
 888458  47.43724, 9.37681  13:07:11  2023-07-16

 [607 rows x 10 columns],
 'df_2':                      measured_at  \
 788582 2020-06-17 11:36:25+00:00
 51301  2020-06-19 11:36:15+00:00
 787813 2020-06-20 11:36:09+00:00
 787512 2020-06-21 11:36:04+00:00
 642955 2020-06-22 11:35:58+00:00
 ...                          ...
 299904 2022-07-25 17:03:58+00:00
 821037 2022-07-26 17:03:52+00:00
 397842 2022-07-29 17:03:35+00:00
 298386 2022-07-30 17:03:30+00:00
 298118 2022-08-02 17:03:14+00:00

                                                  data  \
 788582  {"type": "inquiry", "battery_voltage": 3.584}
 51301   {"type": "inquiry", "battery_voltage": 3.584}
 787813  {"type": "inquiry", "battery_voltage": 3.659}
 787512  {"type": "inquiry", "battery_voltage": 3.649}
 642955  {"type": "inquiry", "battery_voltage": 3.659}
 ...                                               ...
 299904   {"type": "inquiry", "battery_voltage": 3.64}
 821037   {"type": "inquiry", "battery_voltage": 3.63}
 397842  {"type": "inquiry", "battery_voltage": 3.584}
 298386   {"type": "inquiry", "battery_voltage": 3.63}
 298118   {"type": "inquiry", "battery_voltage": 3.64}

                                    device_id           name  \
 788582  eaea0bcc-2970-41e1-8821-29be122a65b0  107114 | 654B
 51301   eaea0bcc-2970-41e1-8821-29be122a65b0  107114 | 654B
 787813  eaea0bcc-2970-41e1-8821-29be122a65b0  107114 | 654B
 787512  eaea0bcc-2970-41e1-8821-29be122a65b0  107114 | 654B
 642955  eaea0bcc-2970-41e1-8821-29be122a65b0  107114 | 654B
 ...                                      ...            ...
 299904  eaea0bcc-2970-41e1-8821-29be122a65b0  107114 | 654B
 821037  eaea0bcc-2970-41e1-8821-29be122a65b0  107114 | 654B
 397842  eaea0bcc-2970-41e1-8821-29be122a65b0  107114 | 654B
 298386  eaea0bcc-2970-41e1-8821-29be122a65b0  107114 | 654B
 298118  eaea0bcc-2970-41e1-8821-29be122a65b0  107114 | 654B

                                           id  \
 788582  fb67d88e-9422-4201-9559-d67486e2e54e
 51301   a012fc59-f3ca-460c-a5a3-f53d4b8c20f7
 787813  903eebc1-b5a6-4a41-960a-b44b87c16b56
 787512  5327c43e-0d84-4e91-be1a-d8fe36638d1e
 642955  bb3b4cc5-70c0-402a-89a9-96f43b2d63c5
 ...                                      ...
 299904  cdc3f42b-e58d-4130-9635-a61ebcfc405a
 821037  0151423f-3f5f-48f7-b24c-6eddeb8697ef
 397842  e70486c2-2bb1-424c-bcc9-be7d46d910ee
 298386  5d2017b9-58a0-4ad7-8ce7-827f167b3a46
 298118  e1326f56-8f92-4b3f-b066-5ee68ad3c0fd

                                                  location  data_distance  \
 788582  {"coordinates": [9.391743082129409, 47.4351625...            NaN
 51301   {"coordinates": [9.391743082129409, 47.4351625...            NaN
 787813  {"coordinates": [9.391743082129409, 47.4351625...            NaN
 787512  {"coordinates": [9.391743082129409, 47.4351625...            NaN
 642955  {"coordinates": [9.391743082129409, 47.4351625...            NaN
 ...                                                   ...            ...
 299904  {"coordinates": [9.391743082129409, 47.4351625...            NaN
 821037  {"coordinates": [9.391743082129409, 47.4351625...            NaN
 397842  {"coordinates": [9.391743082129409, 47.4351625...            NaN
 298386  {"coordinates": [9.391743082129409, 47.4351625...            NaN
 298118  {"coordinates": [9.391743082129409, 47.4351625...            NaN

                                geo_point_2d  time_uct    date_uct
 788582  47.4351625218373, 9.391743082129409  11:36:25  2020-06-17
 51301   47.4351625218373, 9.391743082129409  11:36:15  2020-06-19
 787813  47.4351625218373, 9.391743082129409  11:36:09  2020-06-20
 787512  47.4351625218373, 9.391743082129409  11:36:04  2020-06-21
 642955  47.4351625218373, 9.391743082129409  11:35:58  2020-06-22
 ...                                     ...       ...         ...
 299904  47.4351625218373, 9.391743082129409  17:03:58  2022-07-25
 821037  47.4351625218373, 9.391743082129409  17:03:52  2022-07-26
 397842  47.4351625218373, 9.391743082129409  17:03:35  2022-07-29
 298386  47.4351625218373, 9.391743082129409  17:03:30  2022-07-30
 298118  47.4351625218373, 9.391743082129409  17:03:14  2022-08-02

 [739 rows x 10 columns],
 'df_3':                      measured_at  \
 690033 2020-01-01 00:29:44+00:00
 384762 2020-01-01 00:59:44+00:00
 98071  2020-01-01 01:29:44+00:00
 98065  2020-01-01 01:59:44+00:00
 759133 2020-01-01 02:29:43+00:00
 ...                          ...
 891899 2023-10-22 11:22:01+00:00
 891898 2023-10-22 11:22:05+00:00
 685874 2023-10-23 12:06:40+00:00
 876217 2023-10-23 12:06:44+00:00
 685872 2023-10-23 12:06:51+00:00

                                                      data  \
 690033                                         {"foo": 3}
 384762                                         {"foo": 3}
 98071                                          {"foo": 3}
 98065                                          {"foo": 3}
 759133                                         {"foo": 3}
 ...                                                   ...
 891899  {"type": "inquiry", "firmware_version": "V01.0...
 891898      {"type": "inquiry", "battery_voltage": 3.352}
 685874        {"type": "inquiry", "device_type": "00023"}
 876217  {"type": "inquiry", "firmware_type": "FWR-1010...
 685872       {"type": "inquiry", "battery_voltage": 3.36}

                                    device_id           name  \
 690033  cfcfb74d-b13e-43fb-bc59-9eee4f6be818  107038 | 2B8D
 384762  cfcfb74d-b13e-43fb-bc59-9eee4f6be818  107038 | 2B8D
 98071   cfcfb74d-b13e-43fb-bc59-9eee4f6be818  107038 | 2B8D
 98065   cfcfb74d-b13e-43fb-bc59-9eee4f6be818  107038 | 2B8D
 759133  cfcfb74d-b13e-43fb-bc59-9eee4f6be818  107038 | 2B8D
 ...                                      ...            ...
 891899  cfcfb74d-b13e-43fb-bc59-9eee4f6be818  107038 | 2B8D
 891898  cfcfb74d-b13e-43fb-bc59-9eee4f6be818  107038 | 2B8D
 685874  cfcfb74d-b13e-43fb-bc59-9eee4f6be818  107038 | 2B8D
 876217  cfcfb74d-b13e-43fb-bc59-9eee4f6be818  107038 | 2B8D
 685872  cfcfb74d-b13e-43fb-bc59-9eee4f6be818  107038 | 2B8D

                                           id  \
 690033  d97cbf9b-5c3e-44e6-968c-b5b2f31d961c
 384762  a63dfd4c-11f6-4ede-872c-8e9d09d6494d
 98071   37106e73-582c-4fdf-aa99-e309d7d9e6d3
 98065   0e5d06a9-6121-4dd5-aba3-9d6145435c63
 759133  b3ecc412-d1f3-4e17-aa99-daa66251a5e4
 ...                                      ...
 891899  6eadf8b5-52d5-4572-ad1e-6a320a44d903
 891898  2d5375c4-2d52-4ed3-85da-ec01d9158785
 685874  60940bff-f4d9-4bf0-9053-50258a1aca02
 876217  160607d4-e569-4c49-8f20-8ed7c2763e9e
 685872  21198079-c5bb-4e75-8083-ff601bd543f3

                                                  location  data_distance  \
 690033  {"coordinates": [9.36611, 47.41086], "type": "...            NaN
 384762  {"coordinates": [9.36611, 47.41086], "type": "...            NaN
 98071   {"coordinates": [9.36611, 47.41086], "type": "...            NaN
 98065   {"coordinates": [9.36611, 47.41086], "type": "...            NaN
 759133  {"coordinates": [9.36611, 47.41086], "type": "...            NaN
 ...                                                   ...            ...
 891899  {"coordinates": [9.36611, 47.41086], "type": "...            NaN
 891898  {"coordinates": [9.36611, 47.41086], "type": "...            NaN
 685874  {"coordinates": [9.36611, 47.41086], "type": "...            NaN
 876217  {"coordinates": [9.36611, 47.41086], "type": "...            NaN
 685872  {"coordinates": [9.36611, 47.41086], "type": "...            NaN

              geo_point_2d  time_uct    date_uct
 690033  47.41086, 9.36611  00:29:44  2020-01-01
 384762  47.41086, 9.36611  00:59:44  2020-01-01
 98071   47.41086, 9.36611  01:29:44  2020-01-01
 98065   47.41086, 9.36611  01:59:44  2020-01-01
 759133  47.41086, 9.36611  02:29:43  2020-01-01
 ...                   ...       ...         ...
 891899  47.41086, 9.36611  11:22:01  2023-10-22
 891898  47.41086, 9.36611  11:22:05  2023-10-22
 685874  47.41086, 9.36611  12:06:40  2023-10-23
 876217  47.41086, 9.36611  12:06:44  2023-10-23
 685872  47.41086, 9.36611  12:06:51  2023-10-23

 [9208 rows x 10 columns],
 'df_4':                      measured_at  \
 690035 2020-01-01 00:17:21+00:00
 98083  2020-01-01 00:47:21+00:00
 690028 2020-01-01 01:17:21+00:00
 98067  2020-01-01 01:47:21+00:00
 98061  2020-01-01 02:17:21+00:00
 ...                          ...
 679620 2023-10-09 11:28:59+00:00
 679617 2023-10-09 11:29:06+00:00
 820409 2023-10-10 10:41:46+00:00
 891180 2023-10-10 10:41:54+00:00
 674682 2023-10-10 10:41:57+00:00

                                                      data  \
 690035                                         {"foo": 3}
 98083                                          {"foo": 3}
 690028                                         {"foo": 3}
 98067                                          {"foo": 3}
 98061                                          {"foo": 3}
 ...                                                   ...
 679620  {"type": "inquiry", "firmware_type": "FWR-1010...
 679617      {"type": "inquiry", "battery_voltage": 3.418}
 820409        {"type": "inquiry", "device_type": "00023"}
 891180  {"type": "inquiry", "firmware_version": "V01.0...
 674682      {"type": "inquiry", "battery_voltage": 3.344}

                                    device_id           name  \
 690035  62ec2345-9665-4fd2-9fa7-91ead95dc99b  107031 | 6348
 98083   62ec2345-9665-4fd2-9fa7-91ead95dc99b  107031 | 6348
 690028  62ec2345-9665-4fd2-9fa7-91ead95dc99b  107031 | 6348
 98067   62ec2345-9665-4fd2-9fa7-91ead95dc99b  107031 | 6348
 98061   62ec2345-9665-4fd2-9fa7-91ead95dc99b  107031 | 6348
 ...                                      ...            ...
 679620  62ec2345-9665-4fd2-9fa7-91ead95dc99b  107031 | 6348
 679617  62ec2345-9665-4fd2-9fa7-91ead95dc99b  107031 | 6348
 820409  62ec2345-9665-4fd2-9fa7-91ead95dc99b  107031 | 6348
 891180  62ec2345-9665-4fd2-9fa7-91ead95dc99b  107031 | 6348
 674682  62ec2345-9665-4fd2-9fa7-91ead95dc99b  107031 | 6348

                                           id  \
 690035  40b7b7f0-3fc1-4d69-a33c-511bec6541af
 98083   b68a2232-57be-417c-88ab-ca41bf2d3bf6
 690028  de301f85-9789-43ee-83a2-316a4a276ca5
 98067   d726ca9b-27eb-4de5-92e6-c8a4cfe3e6fc
 98061   f05857f0-04ee-4bb0-ad48-a74935e395c8
 ...                                      ...
 679620  375a6e02-ec6e-4ea2-812a-e11ae8e5ba24
 679617  d367936a-a8de-44c9-9522-1d7a45934715
 820409  5f90dfa6-5089-4fc2-9d3e-9e97de8bc2e4
 891180  830baf14-008a-4305-8aca-6591c421d702
 674682  034192d3-8ddc-42d6-91a9-8131f29927a2

                                                  location  data_distance  \
 690035  {"coordinates": [9.29952, 47.40395], "type": "...            NaN
 98083   {"coordinates": [9.29952, 47.40395], "type": "...            NaN
 690028  {"coordinates": [9.29952, 47.40395], "type": "...            NaN
 98067   {"coordinates": [9.29952, 47.40395], "type": "...            NaN
 98061   {"coordinates": [9.29952, 47.40395], "type": "...            NaN
 ...                                                   ...            ...
 679620  {"coordinates": [9.29952, 47.40395], "type": "...            NaN
 679617  {"coordinates": [9.29952, 47.40395], "type": "...            NaN
 820409  {"coordinates": [9.29952, 47.40395], "type": "...            NaN
 891180  {"coordinates": [9.29952, 47.40395], "type": "...            NaN
 674682  {"coordinates": [9.29952, 47.40395], "type": "...            NaN

              geo_point_2d  time_uct    date_uct
 690035  47.40395, 9.29952  00:17:21  2020-01-01
 98083   47.40395, 9.29952  00:47:21  2020-01-01
 690028  47.40395, 9.29952  01:17:21  2020-01-01
 98067   47.40395, 9.29952  01:47:21  2020-01-01
 98061   47.40395, 9.29952  02:17:21  2020-01-01
 ...                   ...       ...         ...
 679620  47.40395, 9.29952  11:28:59  2023-10-09
 679617  47.40395, 9.29952  11:29:06  2023-10-09
 820409  47.40395, 9.29952  10:41:46  2023-10-10
 891180  47.40395, 9.29952  10:41:54  2023-10-10
 674682  47.40395, 9.29952  10:41:57  2023-10-10

 [8327 rows x 10 columns],
 'df_5':                      measured_at  \
 788652 2020-06-17 08:19:51+00:00
 156473 2020-06-18 08:19:46+00:00
 454480 2020-06-19 08:19:40+00:00
 50909  2020-06-20 08:19:34+00:00
 50507  2020-06-21 08:19:29+00:00
 ...                          ...
 608749 2022-05-17 10:19:45+00:00
 222280 2022-05-18 10:19:39+00:00
 207873 2022-05-19 10:19:33+00:00
 498126 2022-05-20 10:19:28+00:00
 187629 2022-05-21 10:19:22+00:00

                                                  data  \
 788652  {"type": "inquiry", "battery_voltage": 3.621}
 156473  {"type": "inquiry", "battery_voltage": 3.668}
 454480   {"type": "inquiry", "battery_voltage": 3.63}
 50909   {"type": "inquiry", "battery_voltage": 3.659}
 50507   {"type": "inquiry", "battery_voltage": 3.668}
 ...                                               ...
 608749  {"type": "inquiry", "battery_voltage": 3.688}
 222280  {"type": "inquiry", "battery_voltage": 3.678}
 207873  {"type": "inquiry", "battery_voltage": 3.688}
 498126  {"type": "inquiry", "battery_voltage": 3.688}
 187629  {"type": "inquiry", "battery_voltage": 3.668}

                                    device_id           name  \
 788652  3301af3b-a6fe-429e-8b01-c7b71249abdf  107132 | 255E
 156473  3301af3b-a6fe-429e-8b01-c7b71249abdf  107132 | 255E
 454480  3301af3b-a6fe-429e-8b01-c7b71249abdf  107132 | 255E
 50909   3301af3b-a6fe-429e-8b01-c7b71249abdf  107132 | 255E
 50507   3301af3b-a6fe-429e-8b01-c7b71249abdf  107132 | 255E
 ...                                      ...            ...
 608749  3301af3b-a6fe-429e-8b01-c7b71249abdf  107132 | 255E
 222280  3301af3b-a6fe-429e-8b01-c7b71249abdf  107132 | 255E
 207873  3301af3b-a6fe-429e-8b01-c7b71249abdf  107132 | 255E
 498126  3301af3b-a6fe-429e-8b01-c7b71249abdf  107132 | 255E
 187629  3301af3b-a6fe-429e-8b01-c7b71249abdf  107132 | 255E

                                           id  \
 788652  749a7bf4-feb0-4682-8de4-10f6f91a03ce
 156473  495ef829-68a7-46fe-9741-108a0eb06788
 454480  404bfb59-2cc3-497c-9e7b-83e7fc8f6d04
 50909   c2189abd-7ce9-4aa5-904f-c27d9599227f
 50507   23ca73df-b629-4112-a536-e3d50a2391b8
 ...                                      ...
 608749  c87c1fe7-8fb1-4ee6-a758-db373c97a07b
 222280  0736a95b-53b2-4d01-8893-f72eb2a03ffa
 207873  6ddd4ea0-1ca4-491c-81d7-774a2d9f9559
 498126  ade8777e-11fb-47c8-bfea-2e9f74796e10
 187629  4fb46a15-b972-4fa7-8dbb-2b1c68bb2dd5

                                                  location  data_distance  \
 788652  {"coordinates": [9.391814913532329, 47.4351834...            NaN
 156473  {"coordinates": [9.391814913532329, 47.4351834...            NaN
 454480  {"coordinates": [9.391814913532329, 47.4351834...            NaN
 50909   {"coordinates": [9.391814913532329, 47.4351834...            NaN
 50507   {"coordinates": [9.391814913532329, 47.4351834...            NaN
 ...                                                   ...            ...
 608749  {"coordinates": [9.391814913532329, 47.4351834...            NaN
 222280  {"coordinates": [9.391814913532329, 47.4351834...            NaN
 207873  {"coordinates": [9.391814913532329, 47.4351834...            NaN
 498126  {"coordinates": [9.391814913532329, 47.4351834...            NaN
 187629  {"coordinates": [9.391814913532329, 47.4351834...            NaN

                                 geo_point_2d  time_uct    date_uct
 788652  47.43518344164286, 9.391814913532329  08:19:51  2020-06-17
 156473  47.43518344164286, 9.391814913532329  08:19:46  2020-06-18
 454480  47.43518344164286, 9.391814913532329  08:19:40  2020-06-19
 50909   47.43518344164286, 9.391814913532329  08:19:34  2020-06-20
 50507   47.43518344164286, 9.391814913532329  08:19:29  2020-06-21
 ...                                      ...       ...         ...
 608749  47.43518344164286, 9.391814913532329  10:19:45  2022-05-17
 222280  47.43518344164286, 9.391814913532329  10:19:39  2022-05-18
 207873  47.43518344164286, 9.391814913532329  10:19:33  2022-05-19
 498126  47.43518344164286, 9.391814913532329  10:19:28  2022-05-20
 187629  47.43518344164286, 9.391814913532329  10:19:22  2022-05-21


In [39]:
# combining the broken time_df, the broken_time and the create_dataframe functions into one cell

import pandas as pd
from datetime import timedelta, datetime

def broken_time_df(broken_list):
    data = {'Start Date': [], 'End Date': []}
    current_start_date = None

    for item in broken_list:
        # Split each item into its type (Start or End) and the date
        date_type, date_value = item.split(': ')
        date_value = datetime.strptime(date_value, '%Y-%m-%d').date()

        # Check if it's a Start Date or End Date and update the data dictionary
        if date_type == 'Start Date':
            current_start_date = date_value
        elif date_type == 'End Date':
            data['Start Date'].append(current_start_date)
            data['End Date'].append(date_value)

    # Create a DataFrame from the dictionary
    df = pd.DataFrame(data)
    return df

def broken_time(df_device_id):
    global start_time, end_time, broken_list
    
    # Reset variables
    start_time = None
    end_time = None
    broken_list = []
    
    for i in df_device_id["date_uct"]:
        if start_time is None:
            # First timestamp
            start_time = i
            broken_list.append(f"Start Date: {start_time}")
            end_time = start_time

        elif i == end_time:
            continue

        elif i == end_time + timedelta(days=1):
            end_time += timedelta(days=1)

        elif i == end_time + timedelta(days=2):
            end_time += timedelta(days=2)

        else:
            broken_list.append(f"End Date: {end_time}")
         
            start_time = i
            broken_list.append(f"Start Date: {start_time}")
            end_time = start_time

    if end_time is not None:
        broken_list.append(f"End Date: {end_time}")

    return broken_list

def create_dataframes(main_df, column_name, list_of_values):
    # Create an empty dictionary to store DataFrames
    dfs = {}

    # Iterate through the list and create DataFrames
    for i, value in enumerate(list_of_values):
        # Create a new DataFrame based on the condition
        filtered_df = main_df.loc[main_df[column_name] == value].copy()

        # Apply the broken_time function to the filtered DataFrame
        broken_list = broken_time(filtered_df)

        # Convert the broken_list into a DataFrame using broken_time_df
        broken_df = broken_time_df(broken_list)

        # Add the new DataFrame to the dictionary
        dfs[f'df_{i + 1}'] = broken_df

    return dfs



# Call the function to create 25 DataFrames with broken_time and broken_time_df logic applied
result_dfs = create_dataframes(df_nan, 'device_id', nan_device_id_list)
print(result_dfs)

{'df_1':     Start Date    End Date
0   2020-06-17  2020-10-08
1   2020-10-11  2020-11-01
2   2020-11-05  2020-11-13
3   2020-11-16  2021-07-08
4   2021-07-11  2022-01-18
5   2022-01-22  2022-01-22
6   2022-01-27  2022-02-02
7   2022-02-08  2022-02-08
8   2022-02-16  2022-02-16
9   2022-04-09  2022-04-09
10  2022-04-17  2022-04-18
11  2022-12-16  2022-12-18
12  2023-01-21  2023-01-25
13  2023-06-08  2023-06-13
14  2023-07-14  2023-07-16, 'df_2':     Start Date    End Date
0   2020-06-17  2020-07-02
1   2020-07-05  2020-09-09
2   2020-09-12  2020-09-24
3   2020-09-27  2020-10-02
4   2020-10-05  2020-10-07
5   2020-10-10  2020-10-11
6   2020-10-14  2020-10-22
7   2020-10-26  2020-10-26
8   2020-10-29  2020-11-01
9   2020-11-04  2021-05-23
10  2021-05-26  2021-11-18
11  2021-11-21  2022-01-23
12  2022-01-26  2022-01-27
13  2022-01-30  2022-07-26
14  2022-07-29  2022-07-30
15  2022-08-02  2022-08-02, 'df_3':     Start Date    End Date
0   2020-01-01  2020-07-22
1   2020-07-25  2020-10-04
2   2020-10-07  2020-10-14
3   2020-10-18  2020-10-18
4   2020-10-22  2020-10-22
5   2020-10-26  2020-11-08
6   2020-11-11  2020-11-11
7   2020-11-14  2020-11-18
8   2020-11-22  2020-11-23
9   2020-11-26  2021-03-29
10  2021-04-09  2021-06-08
11  2021-06-11  2021-06-16
12  2021-06-19  2021-07-14
13  2021-07-18  2021-08-12
14  2021-08-17  2021-11-30
15  2021-12-03  2022-02-15
16  2022-02-18  2022-03-11
17  2022-03-14  2022-03-24
18  2022-03-27  2022-06-28
19  2022-07-02  2022-10-06
20  2022-10-09  2022-10-11
21  2022-10-15  2022-12-28
22  2022-12-31  2023-01-23
23  2023-01-26  2023-02-05
24  2023-02-08  2023-03-02
25  2023-03-05  2023-03-11
26  2023-03-14  2023-04-24
27  2023-04-27  2023-05-03
28  2023-05-06  2023-05-13
29  2023-05-16  2023-09-02
30  2023-09-05  2023-10-13
31  2023-10-16  2023-10-23, 'df_4':     Start Date    End Date
0   2020-01-01  2020-08-04
1   2020-08-07  2020-10-30
2   2020-11-02  2020-11-05
3   2020-11-08  2020-11-23
4   2020-11-27  2021-03-28
..         ...         ...
69  2023-09-06  2023-09-10
70  2023-09-14  2023-09-15
71  2023-09-18  2023-09-20
72  2023-09-23  2023-09-29
73  2023-10-02  2023-10-10

[74 rows x 2 columns], 'df_5':    Start Date    End Date
0  2020-06-17  2020-10-14
1  2020-10-17  2020-10-22
2  2020-10-25  2020-11-02
3  2020-11-05  2020-11-07
4  2020-11-10  2020-11-16
5  2020-11-23  2021-03-04
6  2021-03-07  2021-04-18
7  2021-04-21  2022-02-08
8  2022-02-11  2022-05-21, 'df_6':    Start Date    End Date
0  2020-01-01  2020-05-07
1  2020-05-11  2020-10-05
2  2020-10-11  2020-10-17
3  2020-10-20  2020-11-03
4  2020-11-06  2020-11-21
5  2020-11-24  2020-11-24
6  2020-11-27  2021-11-08
7  2021-11-11  2022-04-06, 'df_7':    Start Date    End Date
0  2020-06-17  2020-09-29
1  2020-10-02  2020-10-18
2  2020-10-21  2020-10-26
3  2020-10-30  2020-11-07
4  2020-11-11  2020-11-18
5  2020-11-23  2020-12-21
6  2020-12-24  2021-11-22
7  2021-11-25  2021-12-24, 'df_8':    Start Date    End Date
0  2020-01-01  2020-10-16
1  2020-10-19  2020-10-24
2  2020-10-28  2020-11-02
3  2020-11-06  2020-11-08
4  2020-11-11  2021-10-14
5  2021-10-17  2022-04-06, 'df_9':     Start Date    End Date
0   2020-06-18  2020-09-28
1   2020-10-03  2020-10-08
2   2020-10-12  2021-11-20
3   2021-11-23  2022-03-05
4   2022-03-08  2022-09-07
5   2022-09-10  2022-12-20
6   2022-12-24  2023-01-11
7   2023-01-14  2023-02-27
8   2023-03-02  2023-08-25
9   2023-09-02  2023-10-16
10  2023-10-27  2023-11-15
11  2023-11-20  2023-11-22, 'df_10':     Start Date    End Date
0   2020-01-01  2020-09-23
1   2020-09-29  2020-10-16
2   2020-10-19  2020-10-23
3   2020-10-26  2020-10-31
4   2020-11-03  2020-11-08
5   2020-11-11  2021-03-29
6   2021-04-16  2021-05-03
7   2021-05-07  2022-07-27
8   2022-08-10  2022-08-23
9   2022-08-26  2023-04-28
10  2023-05-10  2023-06-15
11  2023-06-20  2023-06-21
12  2023-06-24  2023-06-26, 'df_11':    Start Date    End Date
0  2020-06-17  2020-07-01
1  2020-07-05  2020-07-19
2  2020-07-22  2020-09-29
3  2020-10-03  2020-10-06
4  2020-10-10  2020-10-30
5  2020-11-02  2020-11-15
6  2020-11-19  2022-08-10
7  2022-08-13  2022-10-30
8  2022-11-02  2022-11-29, 'df_12':    Start Date    End Date
0  2020-06-17  2020-07-03
1  2020-07-06  2020-09-29
2  2020-10-03  2020-10-18
3  2020-10-21  2020-10-24
4  2020-10-29  2020-10-31
5  2020-11-03  2021-07-25
6  2021-07-28  2021-10-23, 'df_13':    Start Date    End Date
0  2020-06-17  2020-10-02
1  2020-10-06  2020-10-31
2  2020-11-04  2020-11-23
3  2020-11-26  2023-11-30, 'df_14':    Start Date    End Date
0  2020-01-01  2020-10-02
1  2020-10-05  2020-10-16
2  2020-10-19  2020-11-17
3  2020-11-20  2021-03-29, 'df_15':    Start Date    End Date
0  2020-06-17  2020-10-18
1  2020-10-21  2020-11-04
2  2020-11-07  2022-06-01
3  2022-06-04  2023-11-30, 'df_16':     Start Date    End Date
0   2020-06-17  2020-07-04
1   2020-07-07  2020-09-28
2   2020-10-04  2020-10-15
3   2020-10-18  2020-10-19
4   2020-10-23  2020-10-23
5   2020-10-27  2020-11-02
6   2020-11-05  2020-11-12
7   2020-11-17  2020-11-23
8   2020-11-26  2022-05-07
9   2022-05-10  2022-07-11
10  2022-07-15  2022-07-16
11  2022-07-21  2022-08-24
12  2022-08-27  2022-08-31
13  2022-09-03  2022-09-03
14  2022-09-06  2023-04-11
15  2023-04-14  2023-11-30, 'df_17':    Start Date    End Date
0  2020-01-01  2020-10-08
1  2020-10-11  2020-10-22
2  2020-10-26  2020-11-19
3  2020-11-22  2020-11-23
4  2020-11-27  2022-01-28
5  2022-01-31  2022-07-12
6  2022-07-15  2023-01-18
7  2023-01-21  2023-11-30, 'df_18':    Start Date    End Date
0  2020-06-17  2020-10-02
1  2020-10-05  2020-10-23
2  2020-10-26  2020-11-07
3  2020-11-11  2021-03-24
4  2021-03-27  2021-05-07
5  2021-05-10  2022-04-10
6  2022-04-13  2022-09-01
7  2022-09-05  2023-10-16
8  2023-10-19  2023-10-19, 'df_19':    Start Date    End Date
0  2020-06-17  2020-07-07
1  2020-07-10  2020-10-24
2  2020-10-27  2020-11-21
3  2020-11-24  2021-03-24, 'df_20':     Start Date    End Date
0   2020-06-16  2020-06-19
1   2020-06-22  2020-08-20
2   2020-08-25  2020-08-28
3   2020-08-31  2020-09-06
4   2020-09-09  2020-10-03
5   2020-10-06  2020-10-14
6   2020-10-17  2020-10-30
7   2020-11-02  2020-11-03
8   2020-11-06  2020-11-06
9   2020-11-09  2020-11-15
10  2020-11-19  2020-11-23
11  2020-11-26  2021-01-20, 'df_21':     Start Date    End Date
0   2020-06-17  2020-07-01
1   2020-07-04  2020-10-02
2   2020-10-05  2020-10-24
3   2020-10-28  2020-10-28
4   2020-10-31  2020-11-06
5   2020-11-11  2020-11-14
6   2020-11-17  2020-11-18
7   2020-11-21  2020-11-23
8   2020-11-26  2021-03-12
9   2021-03-16  2021-08-14
10  2021-08-17  2021-11-15
11  2021-11-18  2021-11-23
12  2021-11-27  2021-12-28
13  2021-12-31  2022-01-28
14  2022-01-31  2022-04-07
15  2022-04-10  2022-04-12
16  2022-04-15  2023-03-17
17  2023-03-20  2023-04-24
18  2023-04-27  2023-11-30, 'df_22':    Start Date    End Date
0  2020-06-16  2020-07-02, 'df_23':    Start Date    End Date
0  2020-01-01  2020-06-28
1  2020-07-02  2020-07-08
2  2020-07-11  2020-08-03
3  2020-08-06  2020-08-08, 'df_24':    Start Date    End Date
0  2020-01-01  2020-04-08, 'df_25':    Start Date    End Date
0  2020-01-01  2020-04-28}

In [40]:
# Iterate through the dictionary and print each DataFrame
for key, df in result_dfs.items():
    print(f"DataFrame {key}:")
    print(df)
    print("\n" + "=" * 50 + "\n")

DataFrame df_1:
    Start Date    End Date
0   2020-06-17  2020-10-08
1   2020-10-11  2020-11-01
2   2020-11-05  2020-11-13
3   2020-11-16  2021-07-08
4   2021-07-11  2022-01-18
5   2022-01-22  2022-01-22
6   2022-01-27  2022-02-02
7   2022-02-08  2022-02-08
8   2022-02-16  2022-02-16
9   2022-04-09  2022-04-09
10  2022-04-17  2022-04-18
11  2022-12-16  2022-12-18
12  2023-01-21  2023-01-25
13  2023-06-08  2023-06-13
14  2023-07-14  2023-07-16

==================================================

DataFrame df_2:
    Start Date    End Date
0   2020-06-17  2020-07-02
1   2020-07-05  2020-09-09
2   2020-09-12  2020-09-24
3   2020-09-27  2020-10-02
4   2020-10-05  2020-10-07
5   2020-10-10  2020-10-11
6   2020-10-14  2020-10-22
7   2020-10-26  2020-10-26
8   2020-10-29  2020-11-01
9   2020-11-04  2021-05-23
10  2021-05-26  2021-11-18
11  2021-11-21  2022-01-23
12  2022-01-26  2022-01-27
13  2022-01-30  2022-07-26
14  2022-07-29  2022-07-30
15  2022-08-02  2022-08-02

==================================================

DataFrame df_3:
    Start Date    End Date
0   2020-01-01  2020-07-22
1   2020-07-25  2020-10-04
2   2020-10-07  2020-10-14
3   2020-10-18  2020-10-18
4   2020-10-22  2020-10-22
5   2020-10-26  2020-11-08
6   2020-11-11  2020-11-11
7   2020-11-14  2020-11-18
8   2020-11-22  2020-11-23
9   2020-11-26  2021-03-29
10  2021-04-09  2021-06-08
11  2021-06-11  2021-06-16
12  2021-06-19  2021-07-14
13  2021-07-18  2021-08-12
14  2021-08-17  2021-11-30
15  2021-12-03  2022-02-15
16  2022-02-18  2022-03-11
17  2022-03-14  2022-03-24
18  2022-03-27  2022-06-28
19  2022-07-02  2022-10-06
20  2022-10-09  2022-10-11
21  2022-10-15  2022-12-28
22  2022-12-31  2023-01-23
23  2023-01-26  2023-02-05
24  2023-02-08  2023-03-02
25  2023-03-05  2023-03-11
26  2023-03-14  2023-04-24
27  2023-04-27  2023-05-03
28  2023-05-06  2023-05-13
29  2023-05-16  2023-09-02
30  2023-09-05  2023-10-13
31  2023-10-16  2023-10-23

==================================================

DataFrame df_4:
    Start Date    End Date
0   2020-01-01  2020-08-04
1   2020-08-07  2020-10-30
2   2020-11-02  2020-11-05
3   2020-11-08  2020-11-23
4   2020-11-27  2021-03-28
..         ...         ...
69  2023-09-06  2023-09-10
70  2023-09-14  2023-09-15
71  2023-09-18  2023-09-20
72  2023-09-23  2023-09-29
73  2023-10-02  2023-10-10

[74 rows x 2 columns]

==================================================

DataFrame df_5:
   Start Date    End Date
0  2020-06-17  2020-10-14
1  2020-10-17  2020-10-22
2  2020-10-25  2020-11-02
3  2020-11-05  2020-11-07
4  2020-11-10  2020-11-16
5  2020-11-23  2021-03-04
6  2021-03-07  2021-04-18
7  2021-04-21  2022-02-08
8  2022-02-11  2022-05-21

==================================================

DataFrame df_6:
   Start Date    End Date
0  2020-01-01  2020-05-07
1  2020-05-11  2020-10-05
2  2020-10-11  2020-10-17
3  2020-10-20  2020-11-03
4  2020-11-06  2020-11-21
5  2020-11-24  2020-11-24
6  2020-11-27  2021-11-08
7  2021-11-11  2022-04-06

==================================================

DataFrame df_7:
   Start Date    End Date
0  2020-06-17  2020-09-29
1  2020-10-02  2020-10-18
2  2020-10-21  2020-10-26
3  2020-10-30  2020-11-07
4  2020-11-11  2020-11-18
5  2020-11-23  2020-12-21
6  2020-12-24  2021-11-22
7  2021-11-25  2021-12-24

==================================================

DataFrame df_8:
   Start Date    End Date
0  2020-01-01  2020-10-16
1  2020-10-19  2020-10-24
2  2020-10-28  2020-11-02
3  2020-11-06  2020-11-08
4  2020-11-11  2021-10-14
5  2021-10-17  2022-04-06

==================================================

DataFrame df_9:
    Start Date    End Date
0   2020-06-18  2020-09-28
1   2020-10-03  2020-10-08
2   2020-10-12  2021-11-20
3   2021-11-23  2022-03-05
4   2022-03-08  2022-09-07
5   2022-09-10  2022-12-20
6   2022-12-24  2023-01-11
7   2023-01-14  2023-02-27
8   2023-03-02  2023-08-25
9   2023-09-02  2023-10-16
10  2023-10-27  2023-11-15
11  2023-11-20  2023-11-22

==================================================

DataFrame df_10:
    Start Date    End Date
0   2020-01-01  2020-09-23
1   2020-09-29  2020-10-16
2   2020-10-19  2020-10-23
3   2020-10-26  2020-10-31
4   2020-11-03  2020-11-08
5   2020-11-11  2021-03-29
6   2021-04-16  2021-05-03
7   2021-05-07  2022-07-27
8   2022-08-10  2022-08-23
9   2022-08-26  2023-04-28
10  2023-05-10  2023-06-15
11  2023-06-20  2023-06-21
12  2023-06-24  2023-06-26

==================================================

DataFrame df_11:
   Start Date    End Date
0  2020-06-17  2020-07-01
1  2020-07-05  2020-07-19
2  2020-07-22  2020-09-29
3  2020-10-03  2020-10-06
4  2020-10-10  2020-10-30
5  2020-11-02  2020-11-15
6  2020-11-19  2022-08-10
7  2022-08-13  2022-10-30
8  2022-11-02  2022-11-29

==================================================

DataFrame df_12:
   Start Date    End Date
0  2020-06-17  2020-07-03
1  2020-07-06  2020-09-29
2  2020-10-03  2020-10-18
3  2020-10-21  2020-10-24
4  2020-10-29  2020-10-31
5  2020-11-03  2021-07-25
6  2021-07-28  2021-10-23

==================================================

DataFrame df_13:
   Start Date    End Date
0  2020-06-17  2020-10-02
1  2020-10-06  2020-10-31
2  2020-11-04  2020-11-23
3  2020-11-26  2023-11-30

==================================================

DataFrame df_14:
   Start Date    End Date
0  2020-01-01  2020-10-02
1  2020-10-05  2020-10-16
2  2020-10-19  2020-11-17
3  2020-11-20  2021-03-29

==================================================

DataFrame df_15:
   Start Date    End Date
0  2020-06-17  2020-10-18
1  2020-10-21  2020-11-04
2  2020-11-07  2022-06-01
3  2022-06-04  2023-11-30

==================================================

DataFrame df_16:
    Start Date    End Date
0   2020-06-17  2020-07-04
1   2020-07-07  2020-09-28
2   2020-10-04  2020-10-15
3   2020-10-18  2020-10-19
4   2020-10-23  2020-10-23
5   2020-10-27  2020-11-02
6   2020-11-05  2020-11-12
7   2020-11-17  2020-11-23
8   2020-11-26  2022-05-07
9   2022-05-10  2022-07-11
10  2022-07-15  2022-07-16
11  2022-07-21  2022-08-24
12  2022-08-27  2022-08-31
13  2022-09-03  2022-09-03
14  2022-09-06  2023-04-11
15  2023-04-14  2023-11-30

==================================================

DataFrame df_17:
   Start Date    End Date
0  2020-01-01  2020-10-08
1  2020-10-11  2020-10-22
2  2020-10-26  2020-11-19
3  2020-11-22  2020-11-23
4  2020-11-27  2022-01-28
5  2022-01-31  2022-07-12
6  2022-07-15  2023-01-18
7  2023-01-21  2023-11-30

==================================================

DataFrame df_18:
   Start Date    End Date
0  2020-06-17  2020-10-02
1  2020-10-05  2020-10-23
2  2020-10-26  2020-11-07
3  2020-11-11  2021-03-24
4  2021-03-27  2021-05-07
5  2021-05-10  2022-04-10
6  2022-04-13  2022-09-01
7  2022-09-05  2023-10-16
8  2023-10-19  2023-10-19

==================================================

DataFrame df_19:
   Start Date    End Date
0  2020-06-17  2020-07-07
1  2020-07-10  2020-10-24
2  2020-10-27  2020-11-21
3  2020-11-24  2021-03-24

==================================================

DataFrame df_20:
    Start Date    End Date
0   2020-06-16  2020-06-19
1   2020-06-22  2020-08-20
2   2020-08-25  2020-08-28
3   2020-08-31  2020-09-06
4   2020-09-09  2020-10-03
5   2020-10-06  2020-10-14
6   2020-10-17  2020-10-30
7   2020-11-02  2020-11-03
8   2020-11-06  2020-11-06
9   2020-11-09  2020-11-15
10  2020-11-19  2020-11-23
11  2020-11-26  2021-01-20

==================================================

DataFrame df_21:
    Start Date    End Date
0   2020-06-17  2020-07-01
1   2020-07-04  2020-10-02
2   2020-10-05  2020-10-24
3   2020-10-28  2020-10-28
4   2020-10-31  2020-11-06
5   2020-11-11  2020-11-14
6   2020-11-17  2020-11-18
7   2020-11-21  2020-11-23
8   2020-11-26  2021-03-12
9   2021-03-16  2021-08-14
10  2021-08-17  2021-11-15
11  2021-11-18  2021-11-23
12  2021-11-27  2021-12-28
13  2021-12-31  2022-01-28
14  2022-01-31  2022-04-07
15  2022-04-10  2022-04-12
16  2022-04-15  2023-03-17
17  2023-03-20  2023-04-24
18  2023-04-27  2023-11-30

==================================================

DataFrame df_22:
   Start Date    End Date
0  2020-06-16  2020-07-02

==================================================

DataFrame df_23:
   Start Date    End Date
0  2020-01-01  2020-06-28
1  2020-07-02  2020-07-08
2  2020-07-11  2020-08-03
3  2020-08-06  2020-08-08

==================================================

DataFrame df_24:
   Start Date    End Date
0  2020-01-01  2020-04-08

==================================================

DataFrame df_25:
   Start Date    End Date
0  2020-01-01  2020-04-28

==================================================

In [41]:
# Now inluding device id


# Iterate through the dictionary and print each DataFrame
for key, df in result_dfs.items():
    # Get the index of the current DataFrame in the result_dfs dictionary
    index = int(key.split('_')[1]) - 1

    # Get the corresponding Device ID from the list_of_values
    device_id_value = nan_device_id_list[index]

    print(f"DataFrame {key} - Device ID: {device_id_value}:")
    print(df)
    print("\n" + "=" * 50 + "\n")

DataFrame df_1 - Device ID: 8a6b6d27-9149-40ea-88b6-0c0d7446a0df:
    Start Date    End Date
0   2020-06-17  2020-10-08
1   2020-10-11  2020-11-01
2   2020-11-05  2020-11-13
3   2020-11-16  2021-07-08
4   2021-07-11  2022-01-18
5   2022-01-22  2022-01-22
6   2022-01-27  2022-02-02
7   2022-02-08  2022-02-08
8   2022-02-16  2022-02-16
9   2022-04-09  2022-04-09
10  2022-04-17  2022-04-18
11  2022-12-16  2022-12-18
12  2023-01-21  2023-01-25
13  2023-06-08  2023-06-13
14  2023-07-14  2023-07-16

==================================================

DataFrame df_2 - Device ID: eaea0bcc-2970-41e1-8821-29be122a65b0:
    Start Date    End Date
0   2020-06-17  2020-07-02
1   2020-07-05  2020-09-09
2   2020-09-12  2020-09-24
3   2020-09-27  2020-10-02
4   2020-10-05  2020-10-07
5   2020-10-10  2020-10-11
6   2020-10-14  2020-10-22
7   2020-10-26  2020-10-26
8   2020-10-29  2020-11-01
9   2020-11-04  2021-05-23
10  2021-05-26  2021-11-18
11  2021-11-21  2022-01-23
12  2022-01-26  2022-01-27
13  2022-01-30  2022-07-26
14  2022-07-29  2022-07-30
15  2022-08-02  2022-08-02

==================================================

DataFrame df_3 - Device ID: cfcfb74d-b13e-43fb-bc59-9eee4f6be818:
    Start Date    End Date
0   2020-01-01  2020-07-22
1   2020-07-25  2020-10-04
2   2020-10-07  2020-10-14
3   2020-10-18  2020-10-18
4   2020-10-22  2020-10-22
5   2020-10-26  2020-11-08
6   2020-11-11  2020-11-11
7   2020-11-14  2020-11-18
8   2020-11-22  2020-11-23
9   2020-11-26  2021-03-29
10  2021-04-09  2021-06-08
11  2021-06-11  2021-06-16
12  2021-06-19  2021-07-14
13  2021-07-18  2021-08-12
14  2021-08-17  2021-11-30
15  2021-12-03  2022-02-15
16  2022-02-18  2022-03-11
17  2022-03-14  2022-03-24
18  2022-03-27  2022-06-28
19  2022-07-02  2022-10-06
20  2022-10-09  2022-10-11
21  2022-10-15  2022-12-28
22  2022-12-31  2023-01-23
23  2023-01-26  2023-02-05
24  2023-02-08  2023-03-02
25  2023-03-05  2023-03-11
26  2023-03-14  2023-04-24
27  2023-04-27  2023-05-03
28  2023-05-06  2023-05-13
29  2023-05-16  2023-09-02
30  2023-09-05  2023-10-13
31  2023-10-16  2023-10-23

==================================================

DataFrame df_4 - Device ID: 62ec2345-9665-4fd2-9fa7-91ead95dc99b:
    Start Date    End Date
0   2020-01-01  2020-08-04
1   2020-08-07  2020-10-30
2   2020-11-02  2020-11-05
3   2020-11-08  2020-11-23
4   2020-11-27  2021-03-28
..         ...         ...
69  2023-09-06  2023-09-10
70  2023-09-14  2023-09-15
71  2023-09-18  2023-09-20
72  2023-09-23  2023-09-29
73  2023-10-02  2023-10-10

[74 rows x 2 columns]

==================================================

DataFrame df_5 - Device ID: 3301af3b-a6fe-429e-8b01-c7b71249abdf:
   Start Date    End Date
0  2020-06-17  2020-10-14
1  2020-10-17  2020-10-22
2  2020-10-25  2020-11-02
3  2020-11-05  2020-11-07
4  2020-11-10  2020-11-16
5  2020-11-23  2021-03-04
6  2021-03-07  2021-04-18
7  2021-04-21  2022-02-08
8  2022-02-11  2022-05-21

==================================================

DataFrame df_6 - Device ID: 11d4bcfe-bde2-42bd-8ebc-43ee77012480:
   Start Date    End Date
0  2020-01-01  2020-05-07
1  2020-05-11  2020-10-05
2  2020-10-11  2020-10-17
3  2020-10-20  2020-11-03
4  2020-11-06  2020-11-21
5  2020-11-24  2020-11-24
6  2020-11-27  2021-11-08
7  2021-11-11  2022-04-06

==================================================

DataFrame df_7 - Device ID: e785cb18-96e1-4215-931a-82a731d2ee5a:
   Start Date    End Date
0  2020-06-17  2020-09-29
1  2020-10-02  2020-10-18
2  2020-10-21  2020-10-26
3  2020-10-30  2020-11-07
4  2020-11-11  2020-11-18
5  2020-11-23  2020-12-21
6  2020-12-24  2021-11-22
7  2021-11-25  2021-12-24

==================================================

DataFrame df_8 - Device ID: 36816c9e-3b69-4b8c-b9f7-150b0edf94db:
   Start Date    End Date
0  2020-01-01  2020-10-16
1  2020-10-19  2020-10-24
2  2020-10-28  2020-11-02
3  2020-11-06  2020-11-08
4  2020-11-11  2021-10-14
5  2021-10-17  2022-04-06

==================================================

DataFrame df_9 - Device ID: b4d0f672-6436-483e-a0cd-fab4fe552a8c:
    Start Date    End Date
0   2020-06-18  2020-09-28
1   2020-10-03  2020-10-08
2   2020-10-12  2021-11-20
3   2021-11-23  2022-03-05
4   2022-03-08  2022-09-07
5   2022-09-10  2022-12-20
6   2022-12-24  2023-01-11
7   2023-01-14  2023-02-27
8   2023-03-02  2023-08-25
9   2023-09-02  2023-10-16
10  2023-10-27  2023-11-15
11  2023-11-20  2023-11-22

==================================================

DataFrame df_10 - Device ID: 2e4a8f6d-d398-4749-bc74-a24efa3f5644:
    Start Date    End Date
0   2020-01-01  2020-09-23
1   2020-09-29  2020-10-16
2   2020-10-19  2020-10-23
3   2020-10-26  2020-10-31
4   2020-11-03  2020-11-08
5   2020-11-11  2021-03-29
6   2021-04-16  2021-05-03
7   2021-05-07  2022-07-27
8   2022-08-10  2022-08-23
9   2022-08-26  2023-04-28
10  2023-05-10  2023-06-15
11  2023-06-20  2023-06-21
12  2023-06-24  2023-06-26

==================================================

DataFrame df_11 - Device ID: 5fe079a9-6e53-4a9d-b974-eca5d0916632:
   Start Date    End Date
0  2020-06-17  2020-07-01
1  2020-07-05  2020-07-19
2  2020-07-22  2020-09-29
3  2020-10-03  2020-10-06
4  2020-10-10  2020-10-30
5  2020-11-02  2020-11-15
6  2020-11-19  2022-08-10
7  2022-08-13  2022-10-30
8  2022-11-02  2022-11-29

==================================================

DataFrame df_12 - Device ID: 0b011106-e5fe-4202-92bd-c89abd042249:
   Start Date    End Date
0  2020-06-17  2020-07-03
1  2020-07-06  2020-09-29
2  2020-10-03  2020-10-18
3  2020-10-21  2020-10-24
4  2020-10-29  2020-10-31
5  2020-11-03  2021-07-25
6  2021-07-28  2021-10-23

==================================================

DataFrame df_13 - Device ID: aae16e11-7f7e-4251-9e73-fd836db67b79:
   Start Date    End Date
0  2020-06-17  2020-10-02
1  2020-10-06  2020-10-31
2  2020-11-04  2020-11-23
3  2020-11-26  2023-11-30

==================================================

DataFrame df_14 - Device ID: b5b36857-0f47-4df9-8c8a-0ff431875b18:
   Start Date    End Date
0  2020-01-01  2020-10-02
1  2020-10-05  2020-10-16
2  2020-10-19  2020-11-17
3  2020-11-20  2021-03-29

==================================================

DataFrame df_15 - Device ID: 7f9cad51-8a0c-4fa9-a6d4-8cf649d819ab:
   Start Date    End Date
0  2020-06-17  2020-10-18
1  2020-10-21  2020-11-04
2  2020-11-07  2022-06-01
3  2022-06-04  2023-11-30

==================================================

DataFrame df_16 - Device ID: 496ebab5-e27f-46a4-91bd-28e5086eb594:
    Start Date    End Date
0   2020-06-17  2020-07-04
1   2020-07-07  2020-09-28
2   2020-10-04  2020-10-15
3   2020-10-18  2020-10-19
4   2020-10-23  2020-10-23
5   2020-10-27  2020-11-02
6   2020-11-05  2020-11-12
7   2020-11-17  2020-11-23
8   2020-11-26  2022-05-07
9   2022-05-10  2022-07-11
10  2022-07-15  2022-07-16
11  2022-07-21  2022-08-24
12  2022-08-27  2022-08-31
13  2022-09-03  2022-09-03
14  2022-09-06  2023-04-11
15  2023-04-14  2023-11-30

==================================================

DataFrame df_17 - Device ID: 96e70afa-3ce0-4674-a331-8b85aed97068:
   Start Date    End Date
0  2020-01-01  2020-10-08
1  2020-10-11  2020-10-22
2  2020-10-26  2020-11-19
3  2020-11-22  2020-11-23
4  2020-11-27  2022-01-28
5  2022-01-31  2022-07-12
6  2022-07-15  2023-01-18
7  2023-01-21  2023-11-30

==================================================

DataFrame df_18 - Device ID: 134fc269-ec25-466f-82e7-780beb314108:
   Start Date    End Date
0  2020-06-17  2020-10-02
1  2020-10-05  2020-10-23
2  2020-10-26  2020-11-07
3  2020-11-11  2021-03-24
4  2021-03-27  2021-05-07
5  2021-05-10  2022-04-10
6  2022-04-13  2022-09-01
7  2022-09-05  2023-10-16
8  2023-10-19  2023-10-19

==================================================

DataFrame df_19 - Device ID: 1607ca61-c966-483d-bbfb-d97027d507c1:
   Start Date    End Date
0  2020-06-17  2020-07-07
1  2020-07-10  2020-10-24
2  2020-10-27  2020-11-21
3  2020-11-24  2021-03-24

==================================================

DataFrame df_20 - Device ID: 79d9a5cb-3704-4a21-aedf-5989c70baed0:
    Start Date    End Date
0   2020-06-16  2020-06-19
1   2020-06-22  2020-08-20
2   2020-08-25  2020-08-28
3   2020-08-31  2020-09-06
4   2020-09-09  2020-10-03
5   2020-10-06  2020-10-14
6   2020-10-17  2020-10-30
7   2020-11-02  2020-11-03
8   2020-11-06  2020-11-06
9   2020-11-09  2020-11-15
10  2020-11-19  2020-11-23
11  2020-11-26  2021-01-20

==================================================

DataFrame df_21 - Device ID: a3e91e80-9b8d-4bd6-bbd7-011319e05a0c:
    Start Date    End Date
0   2020-06-17  2020-07-01
1   2020-07-04  2020-10-02
2   2020-10-05  2020-10-24
3   2020-10-28  2020-10-28
4   2020-10-31  2020-11-06
5   2020-11-11  2020-11-14
6   2020-11-17  2020-11-18
7   2020-11-21  2020-11-23
8   2020-11-26  2021-03-12
9   2021-03-16  2021-08-14
10  2021-08-17  2021-11-15
11  2021-11-18  2021-11-23
12  2021-11-27  2021-12-28
13  2021-12-31  2022-01-28
14  2022-01-31  2022-04-07
15  2022-04-10  2022-04-12
16  2022-04-15  2023-03-17
17  2023-03-20  2023-04-24
18  2023-04-27  2023-11-30

==================================================

DataFrame df_22 - Device ID: e3a7cfea-c281-46fe-8758-0bf2388181c0:
   Start Date    End Date
0  2020-06-16  2020-07-02

==================================================

DataFrame df_23 - Device ID: e194deb4-afb0-4c83-aab2-71fcd13ca4e8:
   Start Date    End Date
0  2020-01-01  2020-06-28
1  2020-07-02  2020-07-08
2  2020-07-11  2020-08-03
3  2020-08-06  2020-08-08

==================================================

DataFrame df_24 - Device ID: a82a9f13-4ec0-45bd-a218-4e2cc4ca11bb:
   Start Date    End Date
0  2020-01-01  2020-04-08

==================================================

DataFrame df_25 - Device ID: f97fcfd4-a7a8-4839-958a-334d8c02566c:
   Start Date    End Date
0  2020-01-01  2020-04-28

==================================================